### ISSUE TITLE
long ID number

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4084] opened 2022-04-28 17:58 UTC
I have a model which contains ```1.675e7```, so ```16.75``` million macroparticles. From this I select ```161871``` macroparticles and I list their coordinates and ID's. I expected the ID to be counted from ```0``` to ```16 750 000``` so a ```long``` up to 8 digits but I get also values like ```9 223 372 036 881 183 029``` that is 19 digits.

As you can see in the images below, most of values are made of 7 or 8 digits but sometimes I get a very large number. Is this a bug?

![image](https://user-images.githubusercontent.com/7108691/165817209-8948e318-727e-4d45-bc74-9aa673d554bd.png)

![image](https://user-images.githubusercontent.com/7108691/165816564-0ce93072-2090-40d4-8f99-85a1f6b07f5b.png)

**Comment by sbastrakov** [comment] 2022-04-29 09:01
That is interesting. I am not immediately sure if that is supposed to happen or not, will need to have a more detailed look. Generally,  IDs only have to be unique,  not required to be at any compact range. But such a difference also feels unexpected for me

**Comment by cbontoiu** [comment] 2022-04-29 09:34
By being unique for the whole simulation, I assume that I can use the ID of a macroparticle to check its coordinates (```x```, ```ux```, ```y```, ```uy```) at earlier times. Is that true?

**Comment by sbastrakov** [comment] 2022-04-29 12:05
Yes, IDs are mostly to track a macropatticle between time iterations, as there is no other way to "link" it - indices in output arrays are not stable between iterations.

**Comment by sbastrakov** [comment] 2022-04-29 13:57
I've checked the code that sets initial particle ID to be used for each process. The process involves taking linearized process rank as a 64-bit number and bit-reverting it, so that's how we end up with gigantic numbers for IDs on some ranks. So vastly different numbers you see just mean the macroparticlesparticles were created by different ranks (so they originated in different areas of your domain, but then the ID doesn't change when a macroparticle travels).

All looks fine though, and we have a unit test that checks that ID ranges of different processes won't overlap. So i'll close the issue.

**Closed as completed by sbastrakov** 2022-04-29 13:57 UTC
Labels: question

**Comment by cbontoiu** [comment] 2022-04-29 15:08
A related question: Is there a way to control the seed such that if I run two independent simulations on exactly the same model I end up with exactly the same distribution of macroparticles? I know that if ```PPC``` is large enough (I used 10) there won't be any sensible difference between the two simulations results (particles, fields and derived fields) but I am curious is this can be controlled, maybe here?

```
#pragma once
#include "picongpu/particles/InitFunctors.hpp"

namespace picongpu 
{
   namespace particles 
  {
      using InitPipeline = bmpl::vector<
         CreateDensity< densityProfiles::Geometry, startPosition::Random10ppc, Carbon >,
	 Manipulate<manipulators::unary::RandomPosition, Carbon>,
	 Manipulate< manipulators::ThreeTimesIonized, Carbon >,
	 ManipulateDerive< manipulators::binary::UnboundElectronsTimesWeighting, Carbon, Electrons >
	>; // end InitPipeline
   } // end of particles namespace
} // end of picongpu namespace
```

**Comment by sbastrakov** [comment] 2022-04-29 15:55
I believe that reproducibility should be the default behavior, given you also run on same number of devices along all axes.

Do you observe otherwise?

**Comment by cbontoiu** [comment] 2022-04-29 16:11
> I believe that reproducibility should be the default behavior, given you also run on same number of devices along all axes.
> 
> Do you observe otherwise?

Not at all, and I am not able to see such differences because I run 6 times the same model to get: particles (1), fields (3), field densities (2). So the macroparticles will be available only in the first simulation but the next five simulations also rely on macroparticles, so today I was asked by a colleague if these simulations are absolutely the same in terms of macroparticle distributions. This is how we arrived to the idea of seed and randomness used by ```PIConGPU``` to place those 10 macroparticles in each cell at initialization.

**Comment by sbastrakov** [comment] 2022-04-29 16:47
Okay, so the initial random generator state should be the same and initial sampling of macroparticles also the same (for the latter we do some extra measures to ensure it) as a collection, so overall same set of macroparticles, but may be different order of IDs. That's given your grid and distribution between devices is same.

However note that the repeated simulations would generally not be bitwise-identical anyways due to e.g. parallel reductions performed for current deposition (but not only for this reason). So basically each simulation should produce a valid result with respect to  floating-point arithmetic and parallel scheme used. But those valid results may and will vary for the same setup.

Generally, this variation should be within your sampling and approximation errors. Care only has to be taken when simulating instabilities. So normally it doesn't affect you much and normally you could indeed treat it as exactly same simulation. As a simplistic control mechanism you could collect some lightweight output like energy histograms (its computation overhead and memory consumption are negligible) and compare between runs

**Comment by psychocoderHPC** [comment] 2022-05-02 07:10
@cbontoiu Note: If you run two simulations and give particles an ID there is no guarantee that particle with ID X is in the next simulation doing exactly the same thing or that the ID is given to the same marco particle.
PIConGPU is not deterministic! The reason for this is that there are many places where we using `atomic` operations. Therefore there are always slidely differences in the precision of the field and this will result over time in slidly different results. 
But the overall motion if you not look to only one particle e.g. Phasespace should be the same.
The ID's of macro particles using `Atmic` too and therefore ID's will always be random distributed within a GPU.

**Comment by sbastrakov** [comment] 2022-05-02 07:26
Ah yes, that is a good addition. From my earlier message macroparticles sampling is the same when we treat all macroparticles as an unordered collection (so like a _set_). It's not same in the ordered sense for reasons @psychocoderHPC wrote.
