### ISSUE TITLE
PML creates non-zero remaining fields

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#3723] opened 2021-08-13 14:00 UTC
During @tomaslevyy simulations, he discovered that with the PML absorbers, a non-zero electric field remains in the simulation box. This causes the particles to be be accelerated and move. 
Details will be provided by @tomaslevyy.

**Comment by tomaslevyy** [comment] 2021-08-13 14:21
As Richard commented, in a simulation consisting of a particle under a plane wave laser pulse (polarised on x-axis) , after the passage of the pulse, it remains a -1e8 V/m noisy but constant electric field (Being the pulse maximum 2e13 V/m). This has the effect of a nearly constant acceleration on the x direction, as expected. For the graphs, green discontinuous line is the momentum, with it's values on the right vertical axis.

graph during the pulse:

![plot2](https://user-images.githubusercontent.com/87823051/129371582-b5b38cb0-d3bf-4b57-a7a3-4b32b6c4c343.png)
![plot3](https://user-images.githubusercontent.com/87823051/129371585-8afa32d8-33f1-467e-a51a-acf7f32516d7.png)
![plot4](https://user-images.githubusercontent.com/87823051/129371587-7d90e436-f0bb-4166-a5fe-bc0eb85da473.png)
![plot1](https://user-images.githubusercontent.com/87823051/129371590-ec675eb8-8649-425e-9c00-050f98e59c41.png)

graphs after the pulse:

![plot1](https://user-images.githubusercontent.com/87823051/129370458-e9b7a380-6cc8-4daf-b7a4-26459766b281.png)
![plot2](https://user-images.githubusercontent.com/87823051/129370461-bce1ed60-8039-4388-bebe-ecb304057611.png)
![plot3](https://user-images.githubusercontent.com/87823051/129370465-f6c74b64-f00f-4ddc-a835-ec907e789891.png)
![plot4](https://user-images.githubusercontent.com/87823051/129370467-7056638e-4c5b-4331-aef6-235f90472cfe.png)

**Comment by sbastrakov** [comment] 2021-08-13 14:31
Thanks for additional data @tomaslevyy . PML, as any other field absorber, does not provide absorption to exactly 0. Expected absorption is about 5 orders of magnitude in field values (so 10 orders in energy). From the plots you provided I am not sure how much is the absorption. Is it possible to have Ex at electron position for the whole time duration, with a `log` scale for Ex values?

**Comment by tomaslevyy** [comment] 2021-08-13 14:43
The absorption is from maximum value 2e13 V/m during the pulse to the remaining -1e8 V/m after the pulse. so it's , as you say, the expected order 5 absorption. I didn't know this was the normal thing to happen. Thanks. Even tho, if you want i can provide you with the log plot.

**Comment by sbastrakov** [comment] 2021-08-13 14:50
Okay, so if my initial impression is correct, there is no need for the plot from my side.

Basically, with PML you can make absorption better to have maybe 6 orders, or sometimes even more (with more thickness, and in this case probably also slightly higher `alpha` parameter). But obviously it doesn't change the behavior in principle, just reduces the amplitude of it: if the field is sufficiently above zero given other parameters and floating-point arithmetic used, the particle will be drifting.

**Comment by sbastrakov** [comment] 2021-08-13 14:58
FYI @tomaslevyy we actually had a bug with underabsorbing PML relatively recently. [Here](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3418#issuecomment-743324720) are the results after the fix (so what we have now in `dev`) for a model problem, also used in literature. So on that plot all relative error comes from absorption vs. actually open boundaries, as you can see it is about 1e-5 for CPML which is our default configuration.

**Comment by PrometheusPi** [comment] 2021-08-13 15:04
I think the structure of the remaining field was very surprising. Its constant in one axis and highly oscillating in the other. And exponential damping seems to reflect fields but does not create these global structures. 
@tomaslevyy you had this great 2D plot of the field values where one could see the lines of non-zero fields. Could you upload this plot? @sbastrakov would you please comment whether you would expect such structure with PML?

**Comment by sbastrakov** [comment] 2021-08-13 15:06
Oscillating structure - it is expected (see the plot I linked above). Of course, it does not mean that this particular sturcture is expected, but generally oscillating is not a surprise. I assume constant comes from the fact the laser is axis-aligned?

**Comment by tomaslevyy** [comment] 2021-08-13 15:11
As @PrometheusPi said, the remaining field is not a kind of reflection of the laser, it's more like a heavy modulation around -1e8 V/m and always negative electric fields.
![remaning fields](https://user-images.githubusercontent.com/87823051/129379825-6656f4b6-b260-46cf-8223-5c5729aa2278.png)

**Comment by sbastrakov** [comment] 2021-08-13 15:19
> remaining field is not a kind of reflection of the laser

So yes, while some field comes reflected from the PML area (as again no absorber can fully nullify it in general case), it works differently from just reflecting from this region of the grid, like what happens with exponential absorber. So you won't get your initial laser profile intact but with 10^5 x smaller amplitude, the dependency is much more complicated.

**Comment by tomaslevyy** [comment] 2021-08-13 16:08
I think it's worth saying that with exponential damping, after the passage of the reflected pulse, the remaining E field is 0 (with noise), and there is no acceleration of the particle at the end, so it seems like the undesired effect that happens with pml absorber (electron
acceleration by the remaining field) does not happen with exponential damping, at least with the default parameters. the remaining field with exponential dumping is centered at zero.

plot of Ex in V/m on the plane:
![finalfields](https://user-images.githubusercontent.com/87823051/129387894-e23b08fb-583b-47f6-8ac4-a4407da081e4.png)
![plotd](https://user-images.githubusercontent.com/87823051/129387913-d506c6b1-b348-48f0-8d12-382f7c17542f.png)
![plotc](https://user-images.githubusercontent.com/87823051/129387929-2c5d9bc9-5de3-4d49-ac62-194bd9ec9dad.png)
![plotb](https://user-images.githubusercontent.com/87823051/129387946-7afa6a01-d491-4602-8565-006b86830963.png)
![plota](https://user-images.githubusercontent.com/87823051/129387959-9529e1ac-4848-4685-bc52-f09e51e408ac.png)


Note that the momentum of the electron is not increasing, the electric field is not accelerating the particle. This differs from the pml absorber remaining field.

**Comment by psychocoderHPC** [comment] 2022-03-14 09:25
@PrometheusPi @steindev  Is this issue solved? Could you please summarize the solution?

**Comment by PrometheusPi** [comment] 2022-03-16 09:29
@psychocoderHPC As far as I remember this, issue was not solved. 
We could not settle on whether this is a common artifact of PML, as @sbastrakov suggested, or that a constant background is something that should definitely be avoided (my standpoint). The discussion probably continued, but it is too long ago, perhaps @sbastrakov or @steindev can provide more details.

**Comment by steindev** [comment] 2022-04-04 07:49
With my own setup of a propagating laser pulse I could not see this issue. I believe, the problem is that @tomaslevyy used a **plane wave laser**, which have nonzero field values along the whole transverse plane, in combination with absorbing boundary conditions. This is not advisable.

There should always be some vacuum left between the laser fed into the simulation and the boundary.
My setup does this, and as stated before, I have never seen issues.

**Comment by steindev** [comment] 2022-04-04 07:50
Will close the issue and leave it with the recommendation, to use laser with infinite extent along the transverse plane only in combination with periodic boundary conditions.

**Closed by steindev** 2022-04-04 07:50 UTC
Labels: component: core

**Comment by sbastrakov** [comment] 2022-04-04 08:37
It's also on my plan for this week to re-check this or similar behavior that i suspect may be problematic.
