### ISSUE TITLE
Problems encountered in running LWFA with OpenMP backend

### ISSUE THREAD

**Issue by baobaba13** [ComputationalRadiationPhysics/picongpu#4140] opened 2022-06-08 04:10 UTC
Hello, I recently ran LWFA with CPU on my laptop, but I ran bash tab -s bash -t etc/picongpu/bash/mpirun tpl -c etc/picongpu/1. After CFG $scratch/picruns/001, my PC reported the following error. I don't know what the situation is. I hope someone can help me

Running program...
Note: GPU memory test was skipped as no binary 'cuda_memtest' available. This does not affect PIConGPU, starting it now
unrecognised option '--e_phaseSpace.period'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[31217,1],0]
  Exit code:    1

**Comment by sbastrakov** [comment] 2022-06-08 07:10
Hello @baobaba13 ,

There are two unrelated messages in this output. The first `Note: GPU memory test was skipped as no binary 'cuda_memtest' available. This does not affect PIConGPU, starting it now` is merely that we skip running utility to test your GPU (it's useful on big clusters) as you compiled to run on CPU, so this one you could just ignore.

However, the second one `unrecognised option '--e_phaseSpace.period'` is the error. You requested to run the [phase space plugin](https://picongpu.readthedocs.io/en/latest/usage/plugins/phaseSpace.html#usage-plugins-phasespace) via your .cfg file (you have `--e_phaseSpace.period` option there). This plugin requires that PIConGPU is compiled with openPMD API library dependency, the same is required by most types of PIConGPU output. The dependency is optional, but if it is not found the plugins that need it would be disabled. So you can still run PIConGPU without those plugins, but most output types won't be available. Please see [these instructions](https://picongpu.readthedocs.io/en/latest/install/dependencies.html#openpmd-api) on installing openPMD API.

Generally, you can always see available runtime options (that one normally specifies in .cfg files) for your PIConGPU build with `picongpu -h` (or `.build/picongpu -h` from your build directory).

**Comment by baobaba13** [comment] 2022-06-08 08:21
@sbastrakov First of all, thank you for your  reply. The second error you mentioned is that I didn't install the dependency openpmd API. I checked the two files you mentioned as follows. Because I just came into contact with Ubuntu and scientific computing, I hope to get your explicit help. Thank you very much

```bash
##
## This configuration file is used by PIConGPU's TBG tool to create a
## batch script for PIConGPU runs. For a detailed description of PIConGPU
## configuration files including all available variables, see
##
##                      docs/TBG_macros.cfg
##


#################################
## Section: Required Variables ##
#################################

TBG_wallTime="1:00:00"

TBG_devices_x=1
TBG_devices_y=1
TBG_devices_z=1

TBG_gridSize="192 1024 12"
TBG_steps="2048"

TBG_periodic="--periodic 0 0 1"


#################################
## Section: Optional Variables ##
#################################

# png image output (rough electron density and laser preview)
TBG_pngYX="--e_png.period 100                     \
           --e_png.axis yx --e_png.slicePoint 0.5 \
           --e_png.folder pngElectronsYX"

# energy histogram (electrons, [keV])
TBG_e_histogram="--e_energyHistogram.period 100    \
                 --e_energyHistogram.binCount 1024 \
                 --e_energyHistogram.minEnergy 0 --e_energyHistogram.maxEnergy 1000 \
                 --e_energyHistogram.filter all"

# longitudinal phase space (electrons, [m_e c])
TBG_e_PSypy="--e_phaseSpace.period 100                         \
             --e_phaseSpace.space y --e_phaseSpace.momentum py \
             --e_phaseSpace.min -1.0 --e_phaseSpace.max 1.0    \
             --e_phaseSpace.filter all"

TBG_openPMD="--openPMD.period 100   \
             --openPMD.file simData \
             --openPMD.ext bp \
             --checkpoint.backend openPMD \
             --checkpoint.period 100
             --checkpoint.restart.backend openPMD"

# macro particle counter (electrons, debug information for memory)
TBG_e_macroCount="--e_macroParticlesCount.period 100"

TBG_plugins="!TBG_pngYX                    \
             !TBG_e_histogram              \
             !TBG_e_PSypy                  \
             !TBG_e_macroCount             \
             !TBG_openPMD"

#################################
## Section: Program Parameters ##
#################################

TBG_deviceDist="!TBG_devices_x !TBG_devices_y !TBG_devices_z"

TBG_programParams="-d !TBG_deviceDist \
                   -g !TBG_gridSize   \
                   -s !TBG_steps      \
                   !TBG_periodic     \
                   !TBG_plugins      \
                   --versionOnce"

# TOTAL number of devices
TBG_tasks="$(( TBG_devices_x * TBG_devices_y * TBG_devices_z ))"

"$TBG_cfgPath"/submitAction.sh





Usage picongpu [-d dx=1 dy=1 dz=1] -g width height depth [options]
:
  -h [ --help ]                         print help message and exit
  --validate                            validate command line parameters and 
                                        exit
  -v [ --version ]                      print version information and exit
  -c [ --config ] arg                   Config file(s)

PIConGPU:
  -s [ --steps ] arg                    Simulation steps
  --checkpoint.restart.loop arg (=0)    Number of times to restart the 
                                        simulation after simulation has 
                                        finished (for presentations). Note: 
                                        does not yet work with all plugins, see
                                        issue #1305
  -p [ --percent ] arg (=5)             Print time statistics after p percent 
                                        to stdout
  --checkpoint.restart                  Restart simulation from a checkpoint. 
                                        Requires a valid checkpoint.
  --checkpoint.tryRestart               Try to restart if a checkpoint is 
                                        available else start the simulation 
                                        from scratch.
  --checkpoint.restart.directory arg (=checkpoints)
                                        Directory containing checkpoints for a 
                                        restart
  --checkpoint.restart.step arg         Checkpoint step to restart from
  --checkpoint.period arg               Period for checkpoint creation
  --checkpoint.directory arg (=checkpoints)
                                        Directory for checkpoints
  --author arg                          The author that runs the simulation and
                                        is responsible for created output files
  --mpiDirect                           use device direct for MPI communication
                                        e.g. GPU direct
  --currentInterpolation arg            Current interpolation kind [none, 
                                        binomial] default: none
  --fieldAbsorber arg                   Field absorber kind [exponential, pml] 
                                        default: pml.
                                        When changing absorber, adjust 
                                        parameters in fieldAbsorber.param
  --fieldBackground.duplicateFields     duplicate E and B field storage inside 
                                        field background to improve its 
                                        performance and potentially avoid some 
                                        numerical noise at cost of using more 
                                        memory, only affects the fields with 
                                        activated background
  --e_boundary arg                      Boundary kinds for species 'e' for each
                                        axis. Supported values: default 
                                        (matching --periodic values), periodic,
                                        absorbing, reflecting, thermal
                                        example: --e_boundary absorbing 
                                        periodic reflecting
  --e_boundaryOffset arg                Boundary offsets inwards from global 
                                        domain boundary for species 'e' for 
                                        each axis. Periodic boundaries only 
                                        allow 0 offsets, other kinds support 
                                        non-negative offsets
  --e_boundaryTemperature arg           Boundary temperatures (only affects 
                                        thermal boundaries) for species 'e' for
                                        each axis, in keV.
  --versionOnce                         print version information once and 
                                        start
  -d [ --devices ] arg                  number of devices in each dimension
  -g [ --grid ] arg                     size of the simulation grid
  --gridDist arg                        Regex to describe the static 
                                        distribution of the cells for each 
                                        device,default: equal distribution over
                                        all devices
                                          example:
                                            -d 2 4 1
                                            -g 128 192 12
                                            --gridDist "64{2}" "64,32{2},64"
                                        
  --periodic arg                        specifying whether the grid is periodic
                                        (1) or not (0) in each dimension, 
                                        default: no periodic dimensions
  -m [ --moving ]                       enable sliding/moving window
  --windowMovePoint arg (=0.90000000000000002)
                                        ratio of the global window size in y 
                                        which defines when to start sliding the
                                        window. The window starts sliding at 
                                        the time required to pass the distance 
                                        ofwindowMovePoint * (global window size
                                        in y) when moving with the speed of 
                                        light
  --stopWindow arg (=-1)                stops the window at stimulation step, 
                                        -1 means that window is never stopping
  --autoAdjustGrid arg (=1)             auto adjust the grid size if PIConGPU 
                                        conditions are not fulfilled
  -r [ --numRanksPerDevice ] arg (=1)   set the number of MPI ranks using a 
                                        single device together

Initializers:

PluginController:

Checkpoint:
  --checkpoint                          plugin disabled [compiled without 
                                        dependency openPMD-api]

EnergyFields: calculate the energy of the fields:
  --fields_energy.period arg            enable plugin [for each n-th step]

ResourceLog:
  --resourceLog.period arg              Enable ResourceLog plugin [for each 
                                        n-th step]
  --resourceLog.prefix arg (=resourceLog_)
                                        Set the filename prefix for output file
                                        if a filestream was selected
  --resourceLog.stream arg (=file)      Output stream [stdout, stderr, file]
  --resourceLog.properties arg          List of properties to log [rank, 
                                        position, currentStep, cellCount, 
                                        particleCount]
  --resourceLog.format arg (=json)      Output format of log (pp for pretty 
                                        print) [json, jsonpp, xml, xmlpp]

EnergyParticles: calculate the energy of a species:
  --e_energy.period arg                 compute kinetic and total energy [for 
                                        each n-th step] enable plugin by 
                                        setting a non-zero value
  --e_energy.filter arg                 particle filter: [all]

CalcEmittance: calculate the slice emittance of a species:
  --e_emittance.period arg              compute slice emittance[for each n-th 
                                        step] enable plugin by setting a 
                                        non-zero value
  --e_emittance.filter arg              particle filter: [all]

BinEnergyParticles: calculate a energy histogram of a species:
  --e_energyHistogram.period arg        enable plugin [for each n-th step]
  --e_energyHistogram.filter arg        particle filter: [all]
  --e_energyHistogram.binCount arg      number of bins for the energy range | 
                                        default: 1024
  --e_energyHistogram.minEnergy arg     minEnergy[in keV] | default: 0
  --e_energyHistogram.maxEnergy arg     maxEnergy[in keV]

CountParticles: count macro particles of a species:
  --e_macroParticlesCount.period arg    enable plugin [for each n-th step]

PngPlugin: create png's of a species and fields:
  --e_png.period arg                    enable data output [for each n-th step]
  --e_png.axis arg                      axis which are shown [valid values 
                                        x,y,z] example: yz
  --e_png.slicePoint arg                value range: 0 <= x <= 1 , point of the
                                        slice
  --e_png.folder arg                    folder for output files
```

**Comment by sbastrakov** [comment] 2022-06-08 08:39
Yes, so the first part of what you attached is your .cfg file used for your run. These are converted to command-line parameters of PIConGPU. And the second part shows the parameters available for your build of PIConGPU. (Please use github formatting with ` symbol to paste code/outputs for better readability, as i edited in your last message).

As discussed above, there is no `--e_phaseSpace` as you compiled PIConGPU without openPMD API. We could assist you with installing it. However, in order to not mix up several topics simultaneously, let us first make your current build of PIConGPU run. For that, please edit your .cfg file and remove line `!TBG_plugins      \` (note also to remove the backslash at end of line) and re-run PIConGPU with your original command. Then it should not rely on any optional dependencies, but only on "core" PIConGPU. This way we will see if there are any other issues besides openPMD API first.

**Comment by baobaba13** [comment] 2022-06-08 09:25
@sbastrakov After deleting those two lines, the result is executed according to the original command, but it runs very slowly. Would you like to see if this is normal and correct?

![U $XZLFW96%6 ZH9FY)7CG6](https://user-images.githubusercontent.com/39699124/172581604-3bd15642-52c0-4d64-8125-029457055dae.png)

**Comment by sbastrakov** [comment] 2022-06-08 09:54
The problem is quite large for a CPU, as our normal .cfg file settings are for GPUs. However I think it may be too slow indeed. Two things could have in principle gone wrong:

- Not all CPU cores are utilized, this could be caused e.g. by lack of settings of your OpenMP environment. As a simple check if this happens or not please see CPU utilization via your normal system utilities while PIConGPU is running - it should fully utilize all your cores. If this is not the case, please check [this documentation page](https://picongpu.readthedocs.io/en/latest/install/profile.html#general-notes-on-using-cpus).
- The problem is too large to fit well into your memory and maybe it gets swapped or something similar goes wrong. Again, as a simple check if this happens please check memory utilization while PIConGPU is running. If this is the problem, please reduce grid size in your .cfg file.

**Comment by baobaba13** [comment] 2022-06-08 11:39
@sbastrakov Hello, I have finished running LWFA. However, there is only one log file in my simoutput folder without other simulation results. Perhaps I should install the openpmd plug-in to output simulation results?

![图片](https://user-images.githubusercontent.com/39699124/172607284-4974807f-b5d7-469b-90f5-478ff00f6d59.png)


![图片](https://user-images.githubusercontent.com/39699124/172607326-72c92671-f2f6-4d52-8bb1-d2ef60e5d6a0.png)

**Comment by sbastrakov** [comment] 2022-06-08 11:43
Yes, most PIConGPU output uses openPMD API. To install it, please follow [these instructions](https://picongpu.readthedocs.io/en/latest/install/dependencies.html#openpmd-api). In principle you could go either via spack or from source, both ways are described in that documentation page. I think it's probably better to try from source first in your case.

If you face issues with installing openPMD API itself, you could ask on [their github](https://github.com/openPMD/openPMD-api) for assistance.

After it is installed and added to your environment paths, next time you call `pic-build`, PIConGPU should see it and build with it. It will be shown in the build output of PIConGPU.

**Comment by baobaba13** [comment] 2022-06-08 11:45
OK, thank you very much for your answer. I will try it later and give feedback here

**Comment by baobaba13** [comment] 2022-06-09 01:57
@sbastrakov Hello, under your guidance, I have successfully installed openpmd, as shown in the following figure. However, after I used the     
`pic configure -b" omp2b:native "$home/picinputs/mylwfa` and   `pic build -b" omp2b:native "`commands to build,the build  reached 95%， I encountered the following problems. Could you give me some suggestions.？Thank you.
![图片](https://user-images.githubusercontent.com/39699124/172747520-2673b5ca-bdf0-4afa-9e82-86ff3ca2d9d3.png)

![图片](https://user-images.githubusercontent.com/39699124/172747595-6a625040-4ef2-42f1-856f-1024c6332ada.png)

The following is the complete build display：
![图片](https://user-images.githubusercontent.com/39699124/172756280-683cc726-affa-4e21-92ff-af4fbafa22fe.png)
![图片](https://user-images.githubusercontent.com/39699124/172756306-ebea54b0-d686-48a7-956e-dc089eef8f2f.png)
![图片](https://user-images.githubusercontent.com/39699124/172756316-74079a11-7ddd-407a-b789-933c910df2f7.png)
![图片](https://user-images.githubusercontent.com/39699124/172756335-c71453b6-2577-49e4-8ee8-be0548ea08a8.png)
![图片](https://user-images.githubusercontent.com/39699124/172756357-9b362e0b-236a-4e82-b160-b38d53182a2f.png)
![图片](https://user-images.githubusercontent.com/39699124/172756375-e08e2f3f-7d87-4128-acc1-2188eebbcbcf.png)

**Comment by sbastrakov** [comment] 2022-06-09 07:18
It seems that your compiler crashed while building PIConGPU. Maybe the exact reason is given in the language of your locale between `fatal error: ` and `signal terminated`, but it anyways means something happened to your compiler. Note that it is definitely not related to the warning messages earlier in your output.

Generally, PIConGPU is known to require a lot of memory for compilation, perhaps that is the problem. Note that now with openPMD API available much more code is being compiled relative to what you had originally (as we conditionally enable a lot of code if openPMD API is present), this is probably why it was fine before, but crashes now. However, this setup should generally be on the lighter side, so I am surprised this happens.

How much memory do you have available on the system? If there is a way to not run any other applications while building PIConGPU, that may help. Changing to another compiler may also help.

**Comment by baobaba13** [comment] 2022-06-09 07:33
@sbastrakov Hello, thank you for your reply. The Ubuntu system I am using is 4GB memory, and the version is 18.04. It was installed on the vmvaere workstation on my notebook. The compiler version I use is GCC 8.4.0. Please help me to see whether it is due to insufficient memory or poor compiler version. If I change the compiler, I will update the version or change the type. Thank you very much.

**Comment by sbastrakov** [comment] 2022-06-09 07:50
I think 4 GB memory is generally not sufficient for compiling a complex PIConGPU simulation with openPMD API. While it may be that some setups or compiler work sometimes, i doubt it would make a reliable workflow. Without openPMD API there is much less to compile, but also you wouldn't have most of our output, so that is likely not sufficient for your physics use case. This compilation memory and long compilation times are only specific to PIConGPU, so perhaps other PIC codes could help you there. In my opinion 4 GB is also very small for doing PIC simulations in general, but of course i cannot say without knowing the specifics.

**Comment by baobaba13** [comment] 2022-06-09 08:08
@sbastrakov Hi sbastrakov，What you said is quite correct. I tried to adjust the memory to 10GB and successfully completed pic build When running the simulation later, the same error as last time is encountered, as shown below.
![图片](https://user-images.githubusercontent.com/39699124/172797404-48f2cf21-8025-496a-abe6-283ae65bf2f7.png)
![图片](https://user-images.githubusercontent.com/39699124/172797456-de1ddd3c-94d7-4145-af02-ca79a4b0fe03.png)


I wonder if this is still the problem of openpmd? I'm not sure.

**Comment by sbastrakov** [comment] 2022-06-09 08:40
Oh, sorry. I misunderstood your earlier message as if you only had 4 GB of physical memory overall, not that you set it as limit and actually had more. So then my earlier comment about memory does not apply.

Yes, this looks like an issue with openPMD. I suspect it may be connected to you using the virtual machine, either due to file system, or due to how it interacts with MPI. To investigate it, I suggest taking your existing installation of openPMD API and trying to build and run their examples, as described on their github and readthedocs. This way we will know if the problem is caused by openPMD API itself on your machine or it is on the PIConGPU side. If the problem is purely with openPMD API, please report on their github and hopefully they will help, if it is only with PIConGPU we will investigate further.

**Comment by baobaba13** [comment] 2022-06-09 09:28
@sbastrakov  hi  sbastrakov,I tested the openpmd example without any problem, but when I installed openpmd, I only ran the following commands.
![图片](https://user-images.githubusercontent.com/39699124/172814558-f73aeb3c-74dd-4218-a552-fa2c93761887.png)

 I didn't understand this part, so I didn't operate it. I suspect there is a problem here. I want to hear your suggestions. If you think so, can you give me some detailed guidance on this part? Thank you very much
![图片](https://user-images.githubusercontent.com/39699124/172814526-0c138a78-a5e5-4796-975c-1109133d7cca.png)

**Comment by sbastrakov** [comment] 2022-06-09 09:39
Just to clarify, you did build and run examples included in openPMD API succussfully, e.g. [this one](https://github.com/openPMD/openPMD-api/blob/dev/examples/3_write_serial.cpp) that writes to a file?

If not, please do it first. If that runs fine, then please rebuild PIConGPU in debug mode using [this documentation](https://picongpu.readthedocs.io/en/latest/dev/debugging.html) with the example build command given there and rerun your simulation. It will produce a large output file, please attach it here.

**Comment by baobaba13** [comment] 2022-06-09 12:24
@sbastrakov Hello, I found the file "3_write_serial.cpp" in the subfolder of openPMD, and tried to compile it with `g++-o 3_write_serial 3_ write_serial.cpp`. The following error was reported. It showed that the directory openPMD was not found, but the folder existed. Since I just started Ubuntu, maybe it's because my command is wrong, or I didn't put the `.cpp file` in the correct directory. 
![图片](https://user-images.githubusercontent.com/39699124/172846008-7fbfea64-0e9f-4cdf-ad82-d1a4a3e6cc97.png)

Another problem is that the following errors are reported when building according to the commands in the debugging interface. Maybe， can I delete the call to CUDA in any configuration file？Because my current device does not have a GPU. I'm sorry to delay your precious time with such a simple question. I would appreciate it if you could give me some guidance.
![图片](https://user-images.githubusercontent.com/39699124/172846049-006facbc-7549-4a40-b277-6c8632e87adf.png)

**Comment by sbastrakov** [comment] 2022-06-09 13:16
Okay, let us figure these issues one by one.

First, you need to make sure openPMD API works on your system. As i understand, you already installed it from source using our instructions. Then the examples were also already built in the same build directory. If you didn't change it, that would be ` ~/src/openPMD-api/build` (or if you changed the path from our documentation, adjust acccoringly). Then you could simply go to that directory and run it as `./bin/3_write_serial`. But again, please differentiate between PIConGPU and openPMD API. Questions about openPMD API itself should go to their github, not to here.

**Comment by baobaba13** [comment] 2022-06-09 13:49
@sbastrakov Hi sbastrakov：
According to your instructions, I ran `./bin/3_write_serial` and the results are as follows. I wonder if this can explain that my openpmd can be used.
![图片](https://user-images.githubusercontent.com/39699124/172863031-8e5a1f81-dc7a-4c0a-94be-ec0306af691b.png)

**Comment by sbastrakov** [comment] 2022-06-09 13:55
Okay, so that seems to work. To reproduce what we use in PIConGPU, could you also try running example `5_write_parallel`?

**Comment by baobaba13** [comment] 2022-06-09 13:59
@sbastrakov Like this 
![图片](https://user-images.githubusercontent.com/39699124/172865323-248b13a5-ded0-4431-b16c-1fc0a6c3e7b9.png)

**Comment by sbastrakov** [comment] 2022-06-09 14:04
Great, so writing appears to work as a standalone example, now we should investigate what exactly goes wrong with PIConGPU.

Please first make sure you have enough disk space allocated for output, maybe your virtual machine has a limit. It it does not help, then try building PIConGPU in debug mode as we discussed above. I now realized, that since you are building for OpenMP, the build command for debug should also include the `-b` parameter that you used normally. So something like

```
pic-build -b omp2b -c "-DPIC_VERBOSE=127 -DPMACC_VERBOSE=127 -DPMACC_BLOCKING_KERNEL=ON -DCUPLA_STREAM_ASYNC_ENABLE=OFF"
```

(or if you had `omp2b:native` or so before, use it here as well).

**Comment by baobaba13** [comment] 2022-06-09 15:43
@sbastrakov Hi sbastrakov, under your guidance, I successfully built picongpu, but the simulation seems to be unsuccessful. The following is the output file of the simulation. Is this what you mentioned earlier？
GitHub doesn't seem to be able to upload folders, or can I send it directly to your email address

**Comment by sbastrakov** [comment] 2022-06-09 20:51
Please upload file `output`. Alternatively, one could zip the directory and upload the archive.

**Comment by baobaba13** [comment] 2022-06-10 01:33
@sbastrakov Sorry, GitHub can only upload zip packages, which wastes time. This is my entire simoutput folder. Please help me to see what the problem is.Thank you very much!
[simOutput.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/8875071/simOutput.zip)

**Comment by sbastrakov** [comment] 2022-06-10 11:19
Thank you for attaching the file. It is unfortunately not clear what exactly goes wrong even now. However, it seems like the phase space output wrote something, and then the crash happened for openPMD output or checkpointing. I noticed that there are different file extensions used for the two plugins.

So I think it makes sense to try asking openPMD to also output in hdf5. For that, please change `--openPMD.ext bp` to `--openPMD.ext h5` in your .cfg file and re-run. If this also crashes, please in addition attach also the output in your terminal.

**Comment by baobaba13** [comment] 2022-06-10 13:50
@sbastrakov Hi，sbastrakov:
According to your suggestion,I have changed `--openPMD.ext bp`  to `--openPMD.ext h5`  in my .cfg file and re-run. But the simulation still doesn't seem to run successfully.Here are my modified results and output results.I noticed that there seemed to be two more in the openPMD folder H5 format file.However, these two files are too large. Even after compression, they still have 120MB. GitHub does not seem to support uploading such large files. I wonder whether these two files are important for you to judge the problem
![图片](https://user-images.githubusercontent.com/39699124/173076574-29c6adb7-dfc4-4b23-b443-0b526ebbe82f.png)


[simOutput.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/8879401/simOutput.zip)

**Comment by sbastrakov** [comment] 2022-06-10 14:27
Interesting. So perhaps there is indeed some issue with ADIOS2 output, but not with HDF5. To check it for sure, could you try removing 3 lines with checkpoint options? Taking care of end-of-lines, so that your `TBG_openPMD` is

```
TBG_openPMD="--openPMD.period 100   \
             --openPMD.file simData \
             --openPMD.ext h5"
```

If that still crashes, let us next try a smaller simulation volume as it is hard to tell how much memory does your simulation consume together with output. For that, please reduce values in `TBG_gridSize="192 1024 12"`, e.g. to `96 512 12`

**Comment by baobaba13** [comment] 2022-06-10 17:12
@sbastrakov Hi sbastrakov ，seems that I have got the simulation results of LWFA. I don't know whether this means that I have run successfully. Maybe I need to do some other work.Other files were not uploaded here because they were too large.
![图片](https://user-images.githubusercontent.com/39699124/173116089-8e604833-a4ae-4ffe-9fb0-a7d90b5cc0e1.png)
[simOutput.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/8880777/simOutput.zip)
[output.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/8880811/output.zip)

**Comment by sbastrakov** [comment] 2022-06-13 08:49
Hello @baobaba13 .

Yes, so now it seems to have run. So for your current setup `.h5` format seems to work, but not `.bp`. PIConGPU supports outputting in both, and a user selects by providing `--openPMD.ext h5` and similar `.ext` in a few other places. In principle a user could work with both depending on personal preference and workflows used. Especially for smaller scale simulations, there is normally not a big difference otherwise.

If you would like to investigate what went wrong with `.bp`, we need to again go back to openPMD API. Please then try if it runs fine with this format. The `3_write_serial` I asked you to run earlier uses `.h5` and that worked. You may change [here](https://github.com/openPMD/openPMD-api/blob/20e271b1353caba349a6c7081c0ba84d4723e2a2/examples/3_write_serial.cpp#L44) to `.bp` and try if that works.

**Comment by baobaba13** [comment] 2022-06-13 10:16
@sbastrakov Hi sbastrakov I think. If `.h5` can be used, I don't need to explore it What's wrong with BP.Maybe it would be wise to wait until I really have to use `.bp` .Thank you for your guidance.

**Comment by sbastrakov** [comment] 2022-06-13 10:50
Yes, I think this is a reasonable approach. Since the original problem seems to have been resolved, I am closing this issue. In case you have further questions or problems, feel free to create new github issues for that.

**Closed as completed by sbastrakov** 2022-06-13 10:50 UTC
Labels: question, install

**Comment by baobaba13** [comment] 2022-06-13 10:52
Ok,thanks







------------------ Original ------------------
From: Sergei Bastrakov ***@***.***&gt;
Date: Mon,Jun 13,2022 6:50 PM
To: ComputationalRadiationPhysics/picongpu ***@***.***&gt;
Cc: baobaba13 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [ComputationalRadiationPhysics/picongpu] Problems encountered inrunning LWFA with OpenMP backend (Issue #4140)





 
Yes, I think this is a reasonable approach. Since the original problem seems to have been resolved, I am closing this issue. In case you have further questions or problems, feel free to create new github issues for that.
