### ISSUE TITLE
Some problem in running LWFA

### ISSUE THREAD

**Issue by baobaba13** [ComputationalRadiationPhysics/picongpu#4579] opened 2023-05-29 02:38 UTC
Hi@sbastrakov :
  When I was running LWFA, after passing the pic build, I suddenly encountered the following problem, which I have never encountered before. Can you give me some guidance? I would greatly appreciate it
[output.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/11587721/output.zip)

**Comment by BrianMarre** [comment] 2023-05-30 10:35
sbastrakov has moved on, sorry.

With regards to your error that looks like a compiler error due to insufficient memory to me, maybe you ran out of shared memory?

**Comment by psychocoderHPC** [comment] 2023-05-31 08:46
As @BrianMarre said it looks like you run out of host memory not shared memory. 
Without having more information about your system, GPU and setup this is speculation. I would say the run crashed during IO of derived fields e.g. charge density or ionization if activated.

**Comment by baobaba13** [comment] 2023-05-31 10:06
Hi @psychocoderHPC 
I have checked the remaining memory and it shows that there is enough memory. Based on what you said, I also speculate that the software crashed during operation. However, please provide me with some guidance on how to solve this problem，thanks！

**Comment by baobaba13** [comment] 2023-05-31 10:07
Hi @psychocoderHPC 
I have checked the remaining memory and it shows that there is enough memory. Based on what you said, I also speculate that the software crashed during operation. However, please provide me with some guidance on how to solve this problem，thanks！

**Comment by psychocoderHPC** [comment] 2023-06-01 13:36
@baobaba13  please run

```
cat /proc/cpuinfo
free
nvidia-smi
```

and provide the output.

Please upload the file `tbg/submit.start` and if not secret your param files.

**Comment by baobaba13** [comment] 2023-06-02 02:55
Hi @psychocoderHPC 
I am not sure which files you mentioned, so I have packaged and uploaded both the input file and the run file, using the LWFA example, and the parameters inside have not been changed.Can you give me some advice? I would greatly appreciate it！
[runs.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/11631384/runs.zip)
[picInputs.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/11631387/picInputs.zip)

**Comment by psychocoderHPC** [comment] 2023-06-02 07:51
@baobaba13 Could you please run these commands in your terminal that I can get an overview of your system:

```
cat /proc/cpuinfo
free
nvidia-smi
```

**Comment by baobaba13** [comment] 2023-06-02 08:39
Hi @psychocoderHPC
The result of running the command is as follows，thank you very much for your help！
![result](https://github.com/ComputationalRadiationPhysics/picongpu/assets/39699124/be8ddb0e-a0b5-4d15-b855-c90e01b8441f)

**Comment by psychocoderHPC** [comment] 2023-06-02 09:52
Most likely the problem is that your Xserver is running and you run therefore out of memory. Please edit `memory.param`  of your input set `pic-edit memory` and change

https://github.com/ComputationalRadiationPhysics/picongpu/blob/9987d9c99bc27efe3084efa0814eccc5b5f10339/include/picongpu/param/memory.param#L43

to e.g. `constexpr size_t reservedGpuMemorySize = 2llu * * 1024 * 1024 * 1024;` to keep 2 GiB memory on your GPU free.
Another way is disabling the Xserver.
Please keep in mind if you run an XServer and a single kernel requires more than a few seconds to be executed the Xserver will kick the CUDA kernel. Most likely this will not hit you but I like to point it out.

**Comment by baobaba13** [comment] 2023-06-06 08:51
Hi@psychocoderHPC 
I encountered the following problem while running `pic-build` . Can you give me some suggestions? Thanks！
![image](https://github.com/ComputationalRadiationPhysics/picongpu/assets/39699124/32075e52-bae2-47f8-9c12-161942a31a9d)

**Comment by psychocoderHPC** [comment] 2023-06-06 11:14
Could you please run

```Bash
pic-build 2>&1 | tee compile.txt
```

Your screenshot cuts the first lines of the error and this part is the most important part. All output will be located in `compile.txt`.
You can upload this file.

Most likely you copy pasted my error  from the post before
```
constexpr size_t reservedGpuMemorySize = 2llu * * 1024 * 1024 * 1024;
```
should be

```
constexpr size_t reservedGpuMemorySize = 2llu * 1024 * 1024 * 1024;
```

There was a `* *` in my example.

**Comment by baobaba13** [comment] 2023-06-07 07:56
Hi~ @psychocoderHPC
I have corrected the error and uploaded the `compile.txt` . Could you please give me some suggestions，Thanks！
[compile.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/11674092/compile.txt)

**Comment by psychocoderHPC** [comment] 2023-06-07 09:38
Most likely your error is an incompatibility between boost 1.74 and nvcc with CUDA 10.1.

Could you please use another boost version e.g. boost 1.72.0

There are very often problems with nvcc and boost we try to workaround but it is not always possible. The latest dev branch reduces the required boost components and should work more stable.
If you do not depend on features we have only available in 0.6.0 I suggest to switch to the latest develop branch of PCIonGPU.

**Comment by BrianMarre** [comment] 2023-06-14 08:06
@baobaba13 any update on the status? If you managed to fix your issue, please remember to close the issue, thanks!

**Comment by steindev** [comment] 2023-07-18 08:01
No feedback. I assume it is resolved. Closing. Please reopen if required.

**Closed as completed by steindev** 2023-07-18 08:01 UTC
Labels: question, machine/system
