### ISSUE TITLE
What's up with Axl's mustache?

### ISSUE THREAD

**Issue by bussmann** [ComputationalRadiationPhysics/picongpu#1418] opened 2016-03-29 18:08 UTC
Seriously? I mean I'm gone for a few days and this happens?

**Comment by ax3l** [comment] 2016-03-30 07:40
By coincidence, GitHub just introduced the "saved reply" feature :man: 

![github_saved_reply](https://cloud.githubusercontent.com/assets/1353258/14134889/43b223c2-f65a-11e5-9723-c0201e713792.png)

So here is my reply:

Thank you for your report! Unfortunately I can't reproduce your results, can you please provide more information? What compiler versions did you use? Did you try resetting your environment via `module unload mustache`?

Also, did you try installing [mustache](https://github.com/janl/mustache.js/#where-to-use-mustachejs) in your home?

**Comment by erikzenker** [comment] 2016-03-30 07:52
We introduced recently the "mustache wednesday" ...women are suplied for free :man:

**Comment by bussmann** [comment] 2016-03-30 08:32
Actually, I'm close to adding the "bug" lable to this.
I also cannot remember seeing any PR on this new 'feature', so I'm not sure it was approved by the maintainers.

**Comment by ax3l** [comment] 2016-03-30 08:59
Moustaches are always implemented in forks first, but I guess getting it merged will require a hairy offline discussion.

I thought that's a feature request you are posting here?

**Closed** 2016-04-19 18:44 UTC
Labels: feature, outdated/wontfix
