### ISSUE TITLE
Warning in `CartBuffer.tpp`

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#784] opened 2015-03-27 16:16 UTC
The new pull #773 request bring up a warning .

```
src/libPMacc/include/cuSTL/container/CartBuffer.tpp: In member function ‘virtual void picongpu::TotalDivJ::notify(uint32_t)’:
src/libPMacc/include/cuSTL/container/CartBuffer.tpp:155:1: warning: ‘fieldJ.PMacc::container::CartBuffer<PMacc::math::Vector<float, 3>, 3, PMacc::allocator::EmptyAllocator, mpl_::void_, mpl_::void_>::refCount’ may be used uninitialized in this function [-Wuninitialized]
src/picongpu/include/plugins/TotalDivJ.tpp:82:69: note: ‘fieldJ.PMacc::container::CartBuffer<PMacc::math::Vector<float, 3>, 3, PMacc::allocator::EmptyAllocator, mpl_::void_, mpl_::void_>::refCount’ was declared here
In file included from tmpxft_0000a156_00000000-3_main.cudafe1.stub.c:1:0:
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-unused-local-typedefs" [enabled by default]
```

I don't know why this warning was not shown before, but `PseudoBuffer` call only the empty default constructor of `CartBuffer`. In this case member variables of `CartBuffer` like `refCount` were not initialized. If so it can create `NULL pointer exceptions` or destroy the program stack.

**Comment by ax3l** [comment] 2015-03-27 19:03
@Heikman the first 3 lines are relevant, the warning `-Wno-unused-local-typedefs` is a work around for a [FindCUDA.cmake](http://www.cmake.org/Bug/view.php?id=14415) bug and only occurs on old gnu compilers.

**Comment by Heikman** [comment] 2015-03-29 13:04
I just saw that this is the same issue as #94. We can fix it by removing the TotalDivJ plugin.

**Comment by ax3l** [comment] 2015-03-29 14:00
Close ad duplicate of #94

**Closed by ax3l** 2015-03-29 14:00 UTC
Labels: warning
