### ISSUE TITLE
Number of macro particles between source and derived species do not match

### ISSUE THREAD

**Issue by steindev** [ComputationalRadiationPhysics/picongpu#4446] opened 2023-01-27 23:20 UTC
In my current setup I have 3 electron and one ion species. The three electron species represent (1) a spatially homogenous background distribution, (2) an inhomogenous spatial distribution on top of the homogenous background, and (3) a subsample of the inhomogenous distribution used to calculate radiation. The ion species is supposed to ensure charge neutrality at the beginning of the simulation, but ion movement in general is important for the scenario.

With the following `InitPipeline` I would expect as many ion macro-particles as electron-like macro-particles
```cpp
using InitPipeline = bmpl::vector<
  /* current sheet ions */
CreateDensity<densityProfiles::SechSquare, startPosition::RandomPositionAndWeighting, Ions>
  /* current sheet electrons */
, Derive<Ions, CurrentSheetElectrons>
  /* Derive RadiationElectrons from CurrentSheetElectrons */
, ManipulateDerive<manipulators::DeleteCurrentSheetElectrons, CurrentSheetElectrons, RadiationElectrons, filter::RadiationElectronsSelection>
, particles::FillAllGaps<CurrentSheetElectrons>
  /* background electrons */
, CreateDensity<densityProfiles::Homogenous, startPosition::RandomPositionAndWeighting, BackgroundElectrons>
  /* background ions */
, Derive<BackgroundElectrons, Ions>
  /* Add temperature to particles */
, Manipulate<manipulators::AddTemperature, Ions>
, Manipulate<manipulators::AddTemperature, BackgroundElectrons>
, Manipulate<manipulators::AddTemperature, CurrentSheetElectrons>
, Manipulate<manipulators::AddTemperature, RadiationElectrons>
>;
```
But at simulation start there is a difference between `BackgroundElectrons+CurrentSheetElectrons+RadiationElectrons` and `Ions` of
`902430720+2421593+241305454-1144406016 = 1751751`, according to plugin `macroParticleCounter`. (Names and numbers correspond within this sentence.)

However, when commenting the movement of `CurrentSheetElectrons` to `RadiationElectrons` (including `FillAllGaps`), there is an equal amount of electrons (background+current sheet) and ions!

By the way, the line `ManipulateDerive<manipulators::DeleteCurrentSheetElectrons, CurrentSheetElectrons, RadiationElectrons, filter::RadiationElectronsSelection>` puts 99% of `CurrentSheetElectrons` to `RadiationElectrons` and removes the original macro-particle in the source species `CurrentSheetElectrons` by setting `particleSrc[multiMask_] = 0;` in `manipulators::DeleteCurrentSheetElectrons`. (The filter was actually supposed to put 1% of particles to `RadiationElectrons` but I screwed up operator selection in the respective `if` condition).

Implementation of `manipulators::DeleteCurrentSheetElectrons`
```cpp
struct FunctorDeleteCurrentSheetElectrons
{
    /** Applied to both species after destination species has been created from source species
     *
     * Deletes particle in source species.
     *
     * @tparam T_DestParticle pmacc::Particle, type of the destination particle
     * @tparam T_SrcParticle pmacc::Particle, type of the source particle
     * @tparam T_Args pmacc::Particle, arbitrary number of particles types
     *
     * @param particleDest destination particle
     * @param particleSrc source particle
     * @param ... unused particles
     */
    template<typename T_DestParticle, typename T_SrcParticle, typename... T_Args>
    HDINLINE void operator()(const T_DestParticle, T_SrcParticle& particleSrc, T_Args&&...)
    {
        // delete source particle
        particleSrc[multiMask_] = 0;
    }
    static constexpr char const * name = "delete particle from CurrentSheetElectrons.";
};

using DeleteCurrentSheetElectrons = generic::Free<FunctorDeleteCurrentSheetElectrons>;
```

Implementation of `filter::RadiationElectronsSelection`
```cpp
struct FunctorRadiationElectronsSelection
{
    template< typename T_Rng, typename T_Particle >
    HDINLINE bool operator()(
        T_Rng & rng,
        T_Particle const & particle
    )
    {
        bool result = false;
        if( rng() >= float_X( 0.01 ) )
            result = true;
        return result;
    }
    static constexpr char const * name = "radiationElectronsSelection";

    static constexpr bool isDeterministic = false;
};

using RadiationElectronsSelection = generic::FreeRng<
   FunctorRadiationElectronsSelection,
   pmacc::random::distributions::Uniform< float_X >
>;
```

**Comment by steindev** [comment] 2023-01-27 23:28
Just as a test I reordered the `InitPipeline` to move `FillAllGaps` to the end of the pipeline,
```cpp
using InitPipeline = bmpl::vector<
    /* background electrons */
    CreateDensity<densityProfiles::Homogenous, startPosition::RandomPositionAndWeighting, BackgroundElectrons>
    /* background ions */
    , Derive<BackgroundElectrons, Ions>
    /* Add temperature to background electrons */
    , Manipulate<manipulators::AddTemperature, BackgroundElectrons>
    /* current sheet electrons */
    , CreateDensity<densityProfiles::SechSquare, startPosition::RandomPositionAndWeighting, CurrentSheetElectrons>
    /* current sheet ions */
    , Derive<CurrentSheetElectrons, Ions>
    /* Add temperature to current sheet electrons */
    , Manipulate<manipulators::AddTemperature, CurrentSheetElectrons>
    /* Add temperature to ions */
    , Manipulate<manipulators::AddTemperature, Ions>
    /* Derive RadiationElectrons from CurrentSheetElectrons */
    , ManipulateDerive<manipulators::DeleteCurrentSheetElectrons, CurrentSheetElectrons, RadiationElectrons, filter::RadiationElectronsSelection>
    , particles::FillAllGaps<CurrentSheetElectrons>
>;
```
but the inequality between electrons and ions persists `902430720(BackgroundElectrons) + 239556904(CurrentSheetElectrons) + 2435974(RadiationElectrons) - 1144406016(Ions) = 17582`

**Comment by psychocoderHPC** [comment] 2023-01-30 11:48
I will close the issue. The error is coming from a copy-paste error where the option `ec_boundaryOffset 0 12 0` has been set twice and forgotten for species `er`: 
```bash
--ec_boundary periodic reflecting periodic --ec_boundaryOffset 0 12 0
--er_boundary periodic reflecting periodic --ec_boundaryOffset 0 12 0
```
The reason why there was no error thrown during the start is that we have a bug in PIConGPU since over 10 years. 
We parse `--gridDist`,`--devices`, ... as boost program option multitoken and during the creation of the particle boundary feature the error was copy pasted.

A PR to fix the issue is on the way.

EDIT by @steindev: State initial configuration error more precisely.

**Closed as completed** 2023-01-30 12:57 UTC
Labels: component: core, component: user input

**Comment by psychocoderHPC** [comment] 2023-01-30 13:52
I figured out that parsing many options e.g. `--device` in PIConGPU as boost program_options multitoken is not a bug. This is/was our way how to allow setting values per simulation direction.
In some places, we validate that the user is not giving more than 3 values but for `--<species>_boundaryOffset` we do not validate the number of arguments.

**Comment by psychocoderHPC** [comment] 2023-01-30 15:12
The PR https://github.com/ComputationalRadiationPhysics/picongpu/pull/4447 should avoid the wrong usage in the future.
