### ISSUE TITLE
Benchmark simulations

### ISSUE THREAD

**Issue by HighIander** [ComputationalRadiationPhysics/picongpu#3377] opened 2020-10-08 12:26 UTC
### Synopsis:
We performed a set of "simple" ion acceleration test simulations and compared them against smilei. The results are sometimes in full agreement, sometimes they are off by more than  30%.

### Those are the details:
We simulated a transversely periodic box with a transversely plane laser. Target was pure H+electrons. Other parameters;
[coming soon!]
- cell size
- time step
- ionization
- particles per cell
- laser pulse duration
- traditional absorbing boundaries; laser is outside of absorbing cells

We varied a0 (5,10,20) and n (50,100,200). Our FOM is the evolution of the maximum H energy over time (cut-off edge, i.e. not the single one most energetic ion). 

### Results:
**1. Scanning a0:**
![benchmark2_a05_n200](https://user-images.githubusercontent.com/6409838/95456032-fec04c80-096e-11eb-8d36-cf9e6467a79b.png)
![benchmark2_a010_n200](https://user-images.githubusercontent.com/6409838/95456045-054ec400-096f-11eb-9fa1-2a8d3032f7a0.png)
![benchmark2_a20_n200](https://user-images.githubusercontent.com/6409838/95456060-08e24b00-096f-11eb-9d28-85e0e4f56c82.png)

**2. Scanning n0:**
![benchmark2_a010_n50](https://user-images.githubusercontent.com/6409838/95456145-2a433700-096f-11eb-9792-802ec9dba87f.png)
![benchmark2_a010_n100](https://user-images.githubusercontent.com/6409838/95456152-2d3e2780-096f-11eb-84e1-6897d042e544.png)
![benchmark2_a010_n200](https://user-images.githubusercontent.com/6409838/95456045-054ec400-096f-11eb-9fa1-2a8d3032f7a0.png)

**3. Comparison of the spectrum of a0=20,n=200:**
![picongpu9+smilei3_450_thin_quiet](https://user-images.githubusercontent.com/6409838/95456258-5eb6f300-096f-11eb-97f8-7728d0deb912.png)

**Comment by PrometheusPi** [comment] 2020-10-09 07:58
@HighIander Thanks for providing such a detailed benchmark :+1:. I assume with "quite" you mean quite/regular initialization. Is this correct? Do you observe a similar behavior when choosing random initialization? (A Difference would surprise me, but it would be interesting to see how the start position influence the result in both simulations - and thus might point us into the right direction.)

I do not understand your last plot - I only see red and green lines, no purple orange or blue.

**Comment by sbastrakov** [comment] 2020-10-13 13:59
Just as a safety check, does this setup use complex number math? There is a problem with those #3379 in `dev`, but not in the last release

**Comment by paschk31** [comment] 2020-10-13 16:14
> I do not understand your last plot - I only see red and green lines, no purple orange or blue.

the dark blue was wrong labeling, the blue, orange and green however show 3 smilei simulations that are so identical that they block each other out (which is why the last colour, green, is the only one seen)
of PIConGPU on the other hand you see 9 simulations that are all different in course(even though we made it a quiet start) which points to differences in reproducibility of cases of the two codes

**Comment by psychocoderHPC** [comment] 2020-10-15 06:39
To debug this behaviour I created a minimal example based on @wmles example
https://github.com/psychocoderHPC/picongpu/tree/topic-debugFoil

```
pic-create $PICSRC/examples/FoilDebug/ foildDebug/
pic-build
do tbg -s -t -c etc/picongpu/duenn.cfg runs/esirkepov_tsc_64ppc/$(printf "%04d" $i); done
```

Compare Histogram of one timestep:
```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import gridspec

fig, axlist = plt.subplots(1, 1, figsize=(14, 8))
zeile = 140

prefix="runs/esirkepov_tsc_64ppc"

for nr in range(0, 2):
    arr = np.loadtxt(f"{prefix}/{nr:04d}/simOutput/H_energyHistogram_all.dat", skiprows=1)
    plt.plot(np.linspace(0, 250, 1024)[2:-2], np.convolve(arr[zeile, 2:-2]*1024/250, [0.2]*5, mode='valid'), label=nr)
plt.yscale('log')
plt.xlim([5, 90])


ts = arr[zeile, 30]
time = int(round((ts - 11404) / 3394 * 25))
plt.legend()
plt.xlabel("E_H in MeV")
plt.ylabel("particle density")
```

**Comment by sbastrakov** [comment] 2020-10-19 13:13
Things to try, discussed with @psychocoderHPC 

@![20201019_150006.jpg](https://user-images.githubusercontent.com/6825656/96455430-820a5980-121d-11eb-953f-54038ce1bb6e.jpg)

**Comment by psychocoderHPC** [comment] 2020-10-19 13:31
I manipulated PIConGPU to run `ComputeCurrent`, `copyGuardToExchange` sequential. I used 4ppc per cell with the already posted setup and used for all particles the same starting position within the cell (middle of the cell). With this changes the results in multiple simulations are equal. 
`copyGuardToExchange` is the kernel which is called to send particles over the periodic boundaries. This kernel is packing particles that we can send those. The packing is highly parallel and uses atomic functions which will result in a random order of particles. Later we unpack the particles we receive and add the particles to the existing frame list. This process randomize the order of particles within the the frame linked list. I assume the processing order in the current deposition causes the particle dynamics between different simulation runs.

**Comment by sbastrakov** [comment] 2020-10-19 15:26
I think it can also theoretically be that the `copyGuardToExchange` is somehow buggy in the parallel mode, like there is a data race, or wrong atomic parameters?

**Comment by HighIander** [comment] 2020-10-20 10:29
> @HighIander Thanks for providing such a detailed benchmark 👍. I assume with "quite" you mean quite/regular initialization. Is this correct? 
Yes
> Do you observe a similar behavior when choosing random initialization? (A Difference would surprise me, but it would be interesting to see how the start position influence the result in both simulations - and thus might point us into the right direction.)
Yes
> 
> I do not understand your last plot - I only see red and green lines, no purple orange or blue.
You are right, there is only one smilei simulation

**Comment by ax3l** [comment] 2020-10-21 05:09
Just a few thoughts since I was pinged offline:
- try a convergence scan with more cells and particles
- try the convergence scan with both double and single precision
- consider implementing Galerkin interpolation instead of trilinear interpolation for less noise

**Comment by psychocoderHPC** [comment] 2020-10-21 06:58
I did some simulations with the setup from https://github.com/ComputationalRadiationPhysics/picongpu/issues/3377#issuecomment-708934127

- 80k time steps
- volume 48x20000 cells
- PARAM_RES=384 (twice as high as the default)

# esirkepov_tsc_16x16ppc_80k_res384
- 16x16ppc/species quite start
![image](https://user-images.githubusercontent.com/4037125/96683500-8d26cc00-137a-11eb-98f6-7b552d90355e.png)

# esirkepov_tsc_4x4ppc_80k_res384
- 4x4ppc/species quite start
![image](https://user-images.githubusercontent.com/4037125/96683649-b9dae380-137a-11eb-8d9e-77af6c0e455d.png)

# esirkepov_tsc_16ppc_random_80k_res384
- 16ppc/species random start
![image](https://user-images.githubusercontent.com/4037125/96683737-d840df00-137a-11eb-9ecc-f647e6955b7a.png)

# esirkepov_tsc_64ppc_random_80k_res384
- 64ppc/species random start
![image](https://user-images.githubusercontent.com/4037125/96684166-716ff580-137b-11eb-8a32-d724f0972329.png)

**Comment by ax3l** [comment] 2020-10-21 08:48
Can you do the same in double-precision?

**Comment by psychocoderHPC** [comment] 2020-10-21 09:45
# esirkepov_tsc_16ppc_random_80k_res384_doublePrecision_v100
- double precision
- 16ppc random
![image](https://user-images.githubusercontent.com/4037125/96703140-cc611700-1392-11eb-8807-0a23ae7799c3.png)

**Comment by psychocoderHPC** [comment] 2020-10-23 07:51
esirkepov_tsc_16ppc_random_160k_res768_v100
- single precision
- 16ppc
- resolution 768 factor 2 better in each dimension than the runs before

![image](https://user-images.githubusercontent.com/4037125/96971279-30abe400-1515-11eb-8213-d7c79a63ea47.png)

**Comment by psychocoderHPC** [comment] 2020-10-23 19:28
@steindev helped me to look deeper into this issue: 
The issue is coming from the field solver in combination with the current deposition. There is a numerical issue which introduces a strange instability. We tried also the new Arbitrary Order pusher. Order 4+ is resulting into NAN's.
@steindev will look next week again into that issue.

**Comment by steindev** [comment] 2020-10-26 10:57
So here comes the detailed description of the issue we saw. What I describe in the following are the results of a reproducer I already set up after encountering this issue with @psychocoderHPC before.
The setup consists of a 64x64x64 volume with cubic cells and periodic boundaries in all directions.
A 17 cell thick slice in the x-y plane, located around the center of the volume, is homogeneously filled with electrons.
For initialization `startPosition::Quiet` is used with 2 particles per cell.
Initially, all electrons are assigned a constant drift velocity of `0.5 * CELL_WIDTH / DELTA_T`along the z direction.
We use `particles::shapes::CIC`, `currentSolver::EsirkepovNative`, `particles::pusher::HigueraCary`(due to better accuracy than Boris)

We analyze PIConGPU's checkpoint output after one time step. As expected, the homogeneous density and drift produces a homogeneous current density resulting in a homogeneous `Ez` field in the bulk of the foil, see left picture in the  figure below showing the absolute value of the `Ez` field normalized to its maximum value in order to enhance visibility of deviations and note the logarithmic color scale.
The magnetic `Bx` and `By` fields, however, are not homogeneous in contrast to our expectation.
They are supposed to be zero in the bulk since the Ez field is constant, but they show values different from zero at super cell boundaries for the `By` field and at more positions for the `Bx` field.
![image](https://user-images.githubusercontent.com/26382442/97163205-90f28e00-1780-11eb-9a5a-f02811b20cbb.png)

The inaccuracies seem to be of the order of floating point precision. Running with double-precision decreases the inaccuracy, but does not remove it. See figure below. Note, I had to reduce the super cell size to 4x4x4 due to shared memory limitations.
![image](https://user-images.githubusercontent.com/26382442/97163870-90a6c280-1781-11eb-956e-f4e97b369fb6.png)

The arbitrary order solver (using the CFL time step for Yee) seems to amplify these field irregularities as it develops a pronounced wave like field structure with a super cell wave length whose amplitude exponentially increases before resulting in `nan`s.

**Comment by steindev** [comment] 2020-10-26 13:48
I had to update my previous post. Thanks to @sbastrakov for pointing out a (stupid) error in my analysis.

**Comment by sbastrakov** [comment] 2020-10-26 16:07
So from the updated plots there are slight differences between Ez values in supercells, I guess due to current deposition using different summation orders. And they cause also slight differences of B components from theoretical 0 and between each other. However, all these discrepancies seem low and inevitable, and the fact they cause substantial differences to the test case results is worrying and beg a question if the setup poses an adequate test?

**Comment by psychocoderHPC** [comment] 2020-10-26 17:44
The question is why are so smalldifferences get exponential increased e.g. with the high order field solver.
@steindev could it be we need to decrease the timestep because the higher oder solver has a lower cfl creteria?

btw: I wrote add the weekend a detection for one bit differences and flushed one bit differences in the field solver to zero. For the high order pusher it was not solving the issue but IMO due to the large timestep.
I will push the diff one bit detection later.

**Comment by sbastrakov** [comment] 2020-10-26 17:53
Yes @psychocoderHPC that is indeed a question: maybe something is wrong in the implementation, or we accept a too wide range of parameters for the high-order solver. My question was generally about the setup, since we observed substantial discrepancies in cutoff energies for the standard solver as well.

**Comment by psychocoderHPC** [comment] 2020-10-26 18:08
The discrepancy is because the instability triggered by the precision error is to dominant. I have not tested the orginal test case I posted with the one bit error detection/smoother.
What I tested with @steindev last Friday is to make a hole of one cell (x-direcrion) into the target. This results in very good results with 10 test simulations (2 order pusher). As @steindev said to me it could be that the hole is creating fields which are more dominant than the single bit fluctuation in the current.

**Comment by steindev** [comment] 2020-10-26 18:42
I thought the same and queued a simulation using a tenth of the time step hours ago. Unfortunately, @n01r blocks the resources.

**Comment by psychocoderHPC** [comment] 2020-10-26 19:00
Patch to avoid that two single precision variable values will be subtracted if there is only a one bit difference. The patch is not generic (and hacky) and is only effecting the `curlE` and there the calculation of the x component.

```diff
diff --git a/include/picongpu/fields/differentiation/ForwardDerivative.hpp b/include/picongpu/fields/differentiation/ForwardDerivative.hpp
index b247ee095..e5f2a6375 100644
--- a/include/picongpu/fields/differentiation/ForwardDerivative.hpp
+++ b/include/picongpu/fields/differentiation/ForwardDerivative.hpp
@@ -58,6 +58,11 @@ namespace differentiation
             int
         >::type;
 
+        HDINLINE int _float_as_int(float_X& x) const
+        {
+
+            return *((int*)(&x));
+        }
         /** Return derivative value at the given point
          *
          * @tparam T_DataBox data box type with field data
@@ -72,7 +77,18 @@ namespace differentiation
                 Index,
                 T_direction
             >();
-            return ( data( upperIndex ) - data( Index{} ) ) /
+
+            float_X tmp = (data( upperIndex )[1] - data( Index{} )[1]) ;
+            bool cc = ((0x007fffff & _float_as_int(tmp)) == 0x007fffff) ||  (((0x007fffff ^ _float_as_int(tmp)) & 0x007fffff) == 0x007fffff );
+
+            auto res = ( data( upperIndex ) - data( Index{} ) );
+            if(T_direction==0 && data( Index{} )[1] != data( upperIndex )[1])
+            {
+                res.y() = tmp * float_X(!cc);
+            }
+
+            return res /
                 cellSize[ T_direction ];
         }
     };
```

**Comment by steindev** [comment] 2020-10-27 09:38
The behaviour of the AOFDTD solver really is a numerical stability issue. Compare the following pictures with the CFL determined timestep for Yee (upper) and a tenth of it (lower). Pictures are taken at equal real time (due to the factor ten in Δt)
![image](https://user-images.githubusercontent.com/26382442/97283552-459fb480-1840-11eb-8450-2f1a06d91d1b.png)
![image](https://user-images.githubusercontent.com/26382442/97282459-fad16d00-183e-11eb-8d42-3f8825aba066.png)

**Comment by steindev** [comment] 2020-10-27 10:04
So this explains the instability we have seen with the AOFDTD method. But not the difference in cut-off energies observed with standard Yee scheme...

**Comment by PrometheusPi** [comment] 2020-10-27 10:49
@steindev and me discussed yesterday *offline* the possibility that since the current deposition kernel runs on particle frames and [writes the current atomically into the global data space](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4c91240d28633065a8f04d66c39790063b97122b/include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov.hpp#L239) there will be either neighboring super cells writing small contributions before or after the super cell itself deposited its current. The different order of summation might cause the loss of small current contributions causing errors in the current. 

To test this, I wrote a small python script that models current deposition in 1D for equal velocity particles using 8 cells with 2x4 cells as "super cells". 
For CIC shaped particles, and random distributed particles, there seems to be no difference between super cell summation and random summation:
![grafik](https://user-images.githubusercontent.com/5121158/97291505-50f7dd80-184a-11eb-9866-e78ddbd9b101.png)

I will check higher order shapes and quite initialization. 

What worries me is the high noise level for low ppc.

**Comment by PrometheusPi** [comment] 2020-10-27 11:48
There seems to be no difference between random-addition and super-cell-wise-addition for a quite start either: 
![grafik](https://user-images.githubusercontent.com/5121158/97297692-a637ed00-1852-11eb-9fd7-8ad00aa2a18b.png)

**Comment by PrometheusPi** [comment] 2020-10-27 12:46
Even if the currents cancel in the statical average, there seems to be no difference 
![grafik](https://user-images.githubusercontent.com/5121158/97302958-0a11e400-185a-11eb-8c4b-34eff00b25c6.png)

Surprisingly, the supper-cell-wise-addition performs slightly better.

**Comment by PrometheusPi** [comment] 2020-10-27 13:38
@psychocoderHPC I would thus suspect, that the issue does not arise from numeric errors caused by the parallel execution of `ComputeCurrent`.

**Comment by psychocoderHPC** [comment] 2020-10-27 14:21
> @psychocoderHPC I would thus suspect, that the issue does not arise from numeric errors caused by the parallel execution of `ComputeCurrent`. The uncertainty caused by the particle distribution (either random or uniform) is much greater than the error caused by a partially ordered addition (which honestly surprised me).

I still think it is coming from noice on supercell borders. I saw single bit differences, this difference is than creating a magnetic field. Secondly the computational error in the current deposition is in positive direction (right side of the supercell) larger because the algorithm has a sum over cells in positive direction which is always evaluated from left to right (negative to positive) for each direction.
With the checkerbord which can be used to depositit the current we do accumulate 4 supercells in 2D. So IMO the error is largest on right,bottom in 2D.

**Comment by psychocoderHPC** [comment] 2020-11-05 08:06
> Patch to avoid that two single precision variable values will be subtracted if there is only a one bit difference. The patch is not generic (and hacky) and is only effecting the `curlE` and there the calculation of the x component.
> 
> ```diff
> diff --git a/include/picongpu/fields/differentiation/ForwardDerivative.hpp b/include/picongpu/fields/differentiation/ForwardDerivative.hpp
> index b247ee095..e5f2a6375 100644
> --- a/include/picongpu/fields/differentiation/ForwardDerivative.hpp
> +++ b/include/picongpu/fields/differentiation/ForwardDerivative.hpp
> @@ -58,6 +58,11 @@ namespace differentiation
>              int
>          >::type;
>  
> +        HDINLINE int _float_as_int(float_X& x) const
> +        {
> +
> +            return *((int*)(&x));
> +        }
>          /** Return derivative value at the given point
>           *
>           * @tparam T_DataBox data box type with field data
> @@ -72,7 +77,18 @@ namespace differentiation
>                  Index,
>                  T_direction
>              >();
> -            return ( data( upperIndex ) - data( Index{} ) ) /
> +
> +            float_X tmp = (data( upperIndex )[1] - data( Index{} )[1]) ;
> +            bool cc = ((0x007fffff & _float_as_int(tmp)) == 0x007fffff) ||  (((0x007fffff ^ _float_as_int(tmp)) & 0x007fffff) == 0x007fffff );
> +
> +            auto res = ( data( upperIndex ) - data( Index{} ) );
> +            if(T_direction==0 && data( Index{} )[1] != data( upperIndex )[1])
> +            {
> +                res.y() = tmp * float_X(!cc);
> +            }
> +
> +            return res /
>                  cellSize[ T_direction ];
>          }
>      };
> ```

I tested the simulation the one bit error correction, the fluctuation in the result still exists.

**Comment by psychocoderHPC** [comment] 2020-11-05 08:09
I tested also serial CPU (one core) + one bit correction. The fluctuation in the results still exists. 
In the test simulation I changed the compute order of particles in the compute current for each run.

![image](https://user-images.githubusercontent.com/4037125/98213999-31e20580-1f46-11eb-89cd-1065853e1a7a.png)

**Comment by psychocoderHPC** [comment] 2020-11-05 13:20
after talking with @HighIander decided to test if the fluctuation also happened if we use a slide different charge per particle.
I run on GPU a test where each supercell was calculated sequentially. Each `ion` got a slidly different charge by adding bound electrons for hydrogen to a value between `[0,0.1)` and cloning electrons from this ions. Electrons also got bound electrons and the trait to calculate the charge based on bound electrons got updated to have correct sign for the charge for electrons.

https://github.com/psychocoderHPC/picongpu/blob/7761978c400b2d3861c0a2619c6d20d5dd25a0f3/include/picongpu/traits/attribute/GetCharge.hpp#L72-L75 was changed to
```C++
        return
            frame::getCharge< typename T_Particle::FrameType >() * -1.0_X *
            ( particle[boundElectrons_] - protonNumber ) *
            weighting;
```

![image](https://user-images.githubusercontent.com/4037125/98246033-09700080-1f72-11eb-9601-d4f8c250237a.png)

**Comment by sbastrakov** [comment] 2020-11-05 16:45
After some further investigation attemps and discussion today involving quite a few people, we found out an issue. Not sure yet if that is *the* issue causing this effect. But seems definitely a problem.

The intial temperature in this, and probably some other setups, seems to be chosen so that the corresponding Debye length is not resolved by the grid. (In particular, if no temperature is set at all, no grid could resolve it). A couple of quick tests by @psychocoderHPC to add a minimum temperature so that we resolve Debye length seem to decrease the differences between runs by a lot. This result is so far preliminary, the investigation is to be continued.

**Comment by sbastrakov** [comment] 2020-11-05 17:30
Not sure, but maybe [this paper](https://escholarship.org/content/qt8s18g314/qt8s18g314.pdf) and some of its references are relevant for this issue.

**Comment by HighIander** [comment] 2020-11-05 20:14
That's cracy. I never observed large problems with T=0,but obviously it might be dangerous after all. I'll check the references and try to understand why, thx so far!

**Comment by bussmann** [comment] 2020-11-06 05:28
> That's cracy. I never observed large problems with T=0,but obviously it might be dangerous after all. I'll check the references and try to understand why, thx so far! 

T->0 is one of the well known cases where PIC fails conceptually and produces wrong results. If you have never seen this before, you were either extremely lucky or other effects were hiding/dissipating the problem.

What was the Initial temperature for the SMILEI sims?

**Comment by steindev** [comment] 2020-11-06 09:07
Here is an original paper by Birdsall et al (https://doi.org/10.1016/0021-9991(80)90171-0) which @PrometheusPi found after we encountered the issue the first time where I remembered the effect to be described in the Hockney book as the **cold streaming plasma instability**. In Hockney it is described in ch. 7-3-3 *The Warm-Plasma Approximation*.
Back then we saw it in a bunch acceleration where the beam's divergence increased during free propagation.
Just as now, the issue is resolved by a higher resolution (i.e. reduced Δx) and/or a higher initial bunch divergence/temperature.

**Comment by psychocoderHPC** [comment] 2020-11-06 09:14
Here are my results for the toy setup with 64ppc at timestep 12k (short before first particles left the global volume on the laser side) and timestep 23k (ofter a hand full particles left the volume on the right side of the simulation.
The plot shows 100 simulations with 70 keV initial temperature and 10 simulations with 0 keV temperature.
PIConGPU was running on GPU (V100) with full parallelism and the current deposition strategy `StridedCachedSupercells`.
There is still a fluctuation but the spread is much lower. 
**I move the ball now back to the physicists to correct their setup and to update the documentation of PIConGPU to make all users more aware of these effects.**

@sbastrakov is working on a validator to print a warning after the simulation is initialized if needed.

# step 12k

![11k png](https://user-images.githubusercontent.com/4037125/98347338-93be7000-2017-11eb-88c3-16aacc3ec9a2.png)


# step 23k

![23k](https://user-images.githubusercontent.com/4037125/98347397-a5a01300-2017-11eb-9e2d-7e715e769371.png)

**Comment by steindev** [comment] 2020-11-06 09:24
I can also recommend section 4.1 of the paper (https://doi.org/10.3847/1538-4357/aa6d13) which describes the problem in short.

**Comment by n01r** [comment] 2020-11-06 09:39
> @sbastrakov is working on a validator to print a warning after the simulation is initialized if needed.

It would actually be cool if we could factor in all initial conditions for the validation somehow.
Like, how the chosen resolution, number of particles, particle shape, activated ionization and collision all affect this issue.

**Comment by psychocoderHPC** [comment] 2020-11-06 13:22
To complete the tests:

We checked if ionization(ADK) is helping to reduce the fluctuation

# step 23k

![image](https://user-images.githubusercontent.com/4037125/98370663-35a38400-203b-11eb-8fc8-1df04dd3426b.png)

**Comment by psychocoderHPC** [comment] 2020-11-06 13:24
@steindev ask me to test if reducing the pulse length of the laser (plane wave) is helping too, because reducing the pulse length will end in faster increase of the laser energy.

The simulation is halfing the pulse length

# step 23k

![image](https://user-images.githubusercontent.com/4037125/98371006-c1b5ab80-203b-11eb-8d6c-fa3cbd9d9270.png)

**Comment by bussmann** [comment] 2020-11-06 18:55
Dear all,
I think we need a dedicated approach to testing that brings everybody up to speed.

**Comment by steindev** [comment] 2020-11-23 15:59
@HighIander I think we can close this issue, can't we?

**Comment by psychocoderHPC** [comment] 2020-11-23 16:14
I opened an issue that we do not forget to add a temperature to the foil LCT example #3438

**Closed** 2021-02-16 10:19 UTC
