### ISSUE TITLE
Collisions in over-dense plasma

### ISSUE THREAD

**Issue by Theodotus1243** [ComputationalRadiationPhysics/picongpu#3491] opened 2021-01-13 18:32 UTC
Hi
I have a question that demonstrates my complete lack of understanding of what is going on. It's a shame, but I hope the answer will benefit the PIConGPU project and its repo.
I read this issue #2945 and I want to wish @pordyna good luck in achieving Your goal #3243.

PIC method is collisionless
I am simulating ponderomotive force over-dense plasma pushing. Of course, collisions play a significant role there, which are not exists in the simulation.

For example, here are images of the interaction of a beam with a plasma barrier
Initial temperature = 0eV. Interaction with a laser accelerates electrons.
Do I understand correctly that they fly out from the other side of the barrier like bullets, without distorting their trajectories, without collisions?
What effects can affect distinguish simulation results from experiment?

The question is complex, and I do not hope to get an answer to it. I just want experienced people to point me in the right direction.
___
The Second question 

I'm using initPlaneY = 9 with PML
Will this laser be twice as weak as initPlaneY = 0? Because in fact these are two lasers diverging in different directions. Is the second laser reflected when initPlaneY = 0. 
Or everything is taken into account and there is no need to think about anything. Taken from [this discussion](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3144#issuecomment-574329787) 

What happens if there is no vacuum in the laser initialization zone, as mentioned in [discussion](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3144#issuecomment-574305545)?

___
<img src="https://user-images.githubusercontent.com/32220358/104491688-43e1c380-55db-11eb-93f2-15857fedbc8e.png" width="400"><img src="https://user-images.githubusercontent.com/32220358/104491534-109f3480-55db-11eb-853a-6c8860319eb4.png" width="400">

**Comment by PrometheusPi** [comment] 2021-01-18 13:07
Regarding your first question:
Probably @pordyna, @sbastrakov or @steindev can comment better on the collision module and when adding it will provide a better physics results. I will just briefly outline the physical effects you will model when not using the collisions module. 
If you have electrons propagating through a foil, they will not behave like " like bullets, without distorting their trajectories". Both the "bullet" electrons and the foil plasma particles create electromagnetic fields which mitigates forces between both particle groups. Thus the Coulomb field surrounding your "bullet" electrons will effect the electrons in the foil causing them to move away from the "bullet" electrons. This creates a current and thus electromagnetic fields that act back onto the "bullet" electrons altering their path. The farces are mitigated indirectly by the plasma response. This defines a collision-less plasma. 
Adding the collisions module will model inter particle scattering caused by "close fly-bys". The chance for such effects depends manly on the energies of the "bullet" particles. Please see https://srdata.nist.gov/srd64/ for example cross sections. 
The collisions module will model such elastic scattering process by a simplified binary collisions. (@pordyna Please correct me if I am wrong.)

**Comment by sbastrakov** [comment] 2021-01-18 13:18
@Theodotus1243 regarding your second question. Both laser generation modes in PIConGPU should give correct laser values for cells in area `y > initPlaneY`. The method to achieve it varies for two cases: `initPlaneY = 0` and `initPlaneY > 0`. In the latter case, the cells in layer `0 <= y <= initPlaneY` will have some artificial laser values that are not physical, and result from our laser generation mechanism. So if you have matter in this area it will also be affected by these spurious fields, which is probably not what you want.

**Comment by PrometheusPi** [comment] 2021-01-18 13:19
Regarding your second question: 
The laser amplitude will not be altered by the init plane used. The two lasers you observe originate from how we initialize the laser pulse. We only write the electric field at twice the amplitude to the init plane. Thus, creating two counter propagating laser pulses that have compensating magnetic fields right at the init plane. The laser propagating in -y direction should not e reflected, but should be (mostly) absorbed by the boundary conditions. PML are ideally suited for that. But I am not entirely familiar with how many cells are required for the PML and whether they require [by default also 32](https://github.com/ComputationalRadiationPhysics/picongpu/blob/a54b6665623a4355205eff2c38932776fdfadf44/include/picongpu/param/grid.param#L66-L74) cells as the standard absorbing cells. @sbastrakov could you comment on that? If your init plane is within the PML region, you might see reflections. 

If there is no vacuum in the laser init plane any feedback from current is neglected, since it is not taken into account in the init plane. This holds true for particles that are outside the init plane but whose assignment function overlaps the init plane. This might potentially results in underestimating the particles' response to fields. This is especially relevant for density regions above the critical density.

**Comment by sbastrakov** [comment] 2021-01-18 13:47
Okay, so after additional discussion with @PrometheusPi here is a summary of our answers. Sorry if any confusion was caused @Theodotus1243 .

- When having laser `initPlaneY = 0`, it will be initialized at this position and only propagate to positive y direction. Field absorber (both PML and exponential dampling behave the same, also in the next point) on min Y borber will be disabled while the laser is generated.
- When having laser `initPlaneY > 0` it is compile-time checked that also `initPlaneY > min Y absorber`. In this case you will see the correct laser propagating in positive y direction from `initPlaneY `. There will be also an artificial counter-propagating wave towards negative y direction. Which means you should not have density in area `0 <= y <= initPlaneY` as it would be influenced, and you should not use field values in this area for analysis are they are artificial.
- Otherwise than some more limitations described in the previous point, as a user you don't have to care or adjust other paramters.

Regardless of the laser you should not use field values in `0 <= y <= min Y absorber` and similarly along other boundaries with absorber activated for the same reason, thery are artificial.

For PML size 8 should be good. Note that in `dev` there was recently a fix that improves PML absorption quality. But even before it, was quite good and much better than the exponential dampling absorber.

**Comment by Theodotus1243** [comment] 2021-01-24 09:57
@PrometheusPi, @sbastrakov thanks 
It's answers to my questions

**Comment by Theodotus1243** [comment] 2021-01-24 10:13
@PrometheusPi a question about your "Foil and Collisions" answer
You mentioned "Farces" in this sentence "The farces are mitigated indirectly by the plasma response."
I can neither understand nor guess what this means even knowing that it can be typo
___
Also a thought experiment for which I have next question
The images of the original post show a wall of electrons and ions. According to PIC principles, there can be field fluctuations (electrons are warm) but there can be no static electric field, because there is zero average charge

It turns out that once there is no field, if you run an electron through this barrier, it will fly right through. 
Is not it?
P.S. I just realized that such an experiment is easy to carry out. If you are interested, I can do it and post the results

**Comment by PrometheusPi** [comment] 2021-01-24 14:16
@Theodotus1243 Sorry - this was a typo. I meant **forces**.

**Comment by PrometheusPi** [comment] 2021-01-24 15:25
Regarding your thought experiment. The fluctuations cancled out in (spatial and temporal) average. However, this does not mean that charged particles will not be scattered. On average, their pointing will stay the same, but you will add a random increase in pointing/divergence. See e.g. [Raj et al. PRR 2020](https://doi.org/10.1103/PhysRevResearch.2.023123).

**Comment by steindev** [comment] 2021-02-18 10:25
@Theodotus1243 Are your questions answered satisfactorily? If so, please close the issue. If you have any questions later on, you are of course welcome to open a new issue.

**Closed** 2021-02-18 14:44 UTC
Labels: question
