### ISSUE TITLE
compile error when recompiling previously compiled input

### ISSUE THREAD

**Issue by HighIander** [ComputationalRadiationPhysics/picongpu#3259] opened 2020-05-28 09:36 UTC
When I compile a simulation successfully and then just touch a param file, I cet the information from tbg that I should run `pic-build -f`
However, the following compilation fails with the following error:
```
make[2]: *** No rule to make target `/usr/lib64/libnvidia-ml.so', needed by `build_cuda_memtest/cuda_memtest'.  Stop.
make[1]: *** [build_cuda_memtest/CMakeFiles/cuda_memtest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 48%] Built target picongpu-hostonly
[ 51%] Linking CXX static library libcupla.a
[ 74%] Built target cupla
make: *** [all] Error 2

ERROR: Could not successfully run make install in build directory:
       .build
```

**Comment by sbastrakov** [comment] 2020-05-28 10:06
Interesting, looking at it.

**Comment by sbastrakov** [comment] 2020-05-28 10:21
I could not reproduce it so far. Generally removing the `.build` directory before rebuilding is safer, as it avoids having leftovers from the previous cmake configuration that could lead to unobvious errors. Do you have the same behaviour after removing the `.build` and then rebuilding?

**Comment by HighIander** [comment] 2020-05-28 19:44
No, removing the .build directory manually before the second build resolves the issue, sorry forgot this to mention.

**Comment by sbastrakov** [comment] 2020-05-28 21:28
Should we close it?

**Comment by psychocoderHPC** [comment] 2020-05-29 12:00
> Edit: i suppose `pic-build -f ` is removing the old build results, but not the old cmake configuration. So with the same picongpu.profile activated and otherwise similar environment it should be working fine.

`pic-build -f` is only clearing the cmake cache, removing the cmake configuration would mean you lose all flags you configured e.g. with `ccmake` or with the initial `pic-build` call.

Removing `.build` will help in this case but is different to `-f`

**Comment by psychocoderHPC** [comment] 2020-05-29 12:03
> When I compile a simulation successfully and then just touch a param file, I cet the information from tbg that I should run `pic-build -f`
> However, the following compilation fails with the following error:
> 
> ```
> make[2]: *** No rule to make target `/usr/lib64/libnvidia-ml.so', needed by `build_cuda_memtest/cuda_memtest'.  Stop.
> make[1]: *** [build_cuda_memtest/CMakeFiles/cuda_memtest.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 48%] Built target picongpu-hostonly
> [ 51%] Linking CXX static library libcupla.a
> [ 74%] Built target cupla
> make: *** [all] Error 2
> 
> ERROR: Could not successfully run make install in build directory:
>        .build
> ```

@HighIander could it be that you called the initial `pic-build` on the head node and later started a interactive session and called `pic-build -f`? 
IMO this is the reason for the issue because the environment on the head node and compute node on hemera is different. This is a system issue and should not be handled by PIConGPU. On  a well administrated system this will not happen.

**Comment by sbastrakov** [comment] 2020-09-24 09:38
@HighIander should we close this issue?

**Comment by HighIander** [comment] 2020-09-24 12:49
Yes :-)

**Closed** 2020-09-24 12:51 UTC
Labels: install, question
