### ISSUE TITLE
partial particle tracking and field output

### ISSUE THREAD

**Issue by BrianMarre** [ComputationalRadiationPhysics/picongpu#3666] opened 2021-07-02 07:48 UTC
It would be useful to be able to only output a certain portion of all tracked particles.

As in we determine in a param file a percentage to write of a given species with particle tracking and want to only write the particle position and ids (or particle data) of this subsection of particles.

Whether a given particle is included in the output should be determined on particle creation and should not change over time.
(Probably by adding a simple boolean switch and setting it randomly upon particle creation.)

The usual workaround of different species, one with particle tracing and one without, is cumbersome, since artificially separating a species means also artificially disallowing their interaction for purposes of particle creation or not having a set percentage of tracked particles.
Example: We start with a slightly ionised ions with partial particle tracking, we want to use ionization in our simulation. We can either allow **only** the tracked ion portion to create tracked electrons or both but the latter introduces a non constant  percentage of tracked particles or requires a special case in the ionization algorithm to randomly generate tracked or non tracked electrons.

A particle output switch upon creation would be much simpler in implementation, while a little more memory intensive, since all particles would have a particle-ID, but not all would be tracked.

Same would also be useful for field output.
As in output only an evenly distributed percentage of field values of the entire simulation space.

**Comment by pordyna** [comment] 2021-07-02 09:40
I think the problem is that we store particle data in such a way that it is easy to access and write out all particles from one species . One would need to copy ( for each attribute that is written) the entries for particles marked as tracking particles to some new continuous memory. So we would need to go over all particles on host (sth that we only do on device) or we would need extra device buffer for this tracking particles if we would like to do the filtering on device. We could maybe move all tracking particles to the an extra tracing species before writing output and move them back afterwards but this would be probably too much overhead.

So I'm not sure if that would be so easy to implement but I agree this sounds useful.

**Comment by sbastrakov** [comment] 2021-07-02 10:50
Not sure if I misunderstood your suggestion @BrianMarre . But isn't it avaialble now with a filter?

**Comment by BrianMarre** [comment] 2021-07-02 11:08
Wouldn't know how to do it. Maybe we need an example for something like this?

**Comment by sbastrakov** [comment] 2021-07-02 11:14
Fair point, it is not the most well-documented feature. [Here](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3623#issuecomment-853785229) is an example of a filter. Of course, the internals can be done to account for a specific species or particle attributes instead.

**Comment by sbastrakov** [comment] 2021-07-02 11:16
To add up. If you want to filter out particles of some species (by attribute value or somehow else) but not others you can do it with restricting the `T_Particle` in that `operator()`. Basically, have one "branch" to accept all for non-relevant species and one that does the filtering you want for the species (one or multiple) you want.

**Comment by pordyna** [comment] 2021-07-02 11:21
@sbastrakov how can I chose filters for the `openPMD` plugin? I have only seen `species_all` as source.

**Comment by sbastrakov** [comment] 2021-07-02 11:23
Those are sources. Filters are set in particleFilters.param and always applied.

**Comment by pordyna** [comment] 2021-07-02 11:37
@sbastrakov so with 4 Filters on in `AllParticleFilters` and `species_all` I would get in the openPMD output 4 patches for each species? What If I only want to write particle data for particles passing a specific filter?  Ohter plugins (like energy histogram) have the `filter` run time option. Is there  `openPMD.filter` and it is just undocumented?

**Comment by sbastrakov** [comment] 2021-07-02 12:54
Okay, so after investigating how it actually works. There is no `openPMD.filter` like in some other plugins. However, by design it supports all combinations of source + filter. You can see it in the help when looking at possible values of `openPMD.aource` -- that will match your compiled setup. So it seems with a custom filter, it is enough to define it, and then select appropriate combinations as sources.

**Comment by sbastrakov** [comment] 2021-07-02 13:02
I will extend the openPMD plugin documentation to make this source + filter idea more clear. As it is really cool, and I didn't even fully understand it before, and seeminly I am not alone there

**Comment by pordyna** [comment] 2021-07-02 13:03
@sbastrakov yes this is indeed really cool :D and I had no idea. Thanks!

**Comment by PrometheusPi** [comment] 2021-07-08 16:01
@BrianMarre If I understand your initial task corretly, you could have particles with IDs and filter for specific particle IDs, like `particleID % 10 == 0` to only extract every 10th particle. This would keep particles within a species but would allow to output a reduced set of particles only while ensuring the same particles are outputed with every dump.
 (This assumes that the particle IDs are somehow uniformly distributed.)

**Comment by sbastrakov** [comment] 2021-07-08 16:11
I think this should work in practice. It is also possible as @BrianMarre initially suggested to have a special attribute and initialize it during particle creation (or via a manipulation later) as one wants. And then have a filter based on this attribute value. @PrometheusPi is basically a special case with the attribute being equal to `id % 10` (but of course not taking extra memory then).

**Comment by sbastrakov** [comment] 2021-07-29 15:07
@BrianMarre does discussion here answer your original question? If so, feel free to close the issue.

**Closed** 2022-09-05 12:52 UTC
Labels: question
