### ISSUE TITLE
cudaErrorMisalignedAddress on restart

### ISSUE THREAD

**Issue by ervw12** [ComputationalRadiationPhysics/picongpu#3841] opened 2021-10-04 07:25 UTC
I have problems restarting my simulations after reaching the walltime clock limit. The stderr file gives me the following error:

```
 terminate called after throwing an instance of 'std::runtime_error'
   what():  /u/user/src/picongpu/thirdParty/cupla/alpaka/include/alpaka/event/EventUniformCudaHipRt.hpp(175) 'ret = ALPAKA_API_PREFIX(EventQuery)(event.m_spEventImpl->m_UniformCudaHipEvent)' returned error  : 'cudaErrorMisalignedAddress': 'misaligned address'!
 terminate called after throwing an instance of 'std::runtime_error'
   what():  /u/user/src/picongpu/thirdParty/cupla/alpaka/include/alpaka/event/EventUniformCudaHipRt.hpp(175) 'ret = ALPAKA_API_PREFIX(EventQuery)(event.m_spEventImpl->m_UniformCudaHipEvent)' returned error  : 'cudaErrorMisalignedAddress': 'misaligned address'!
 terminate called after throwing an instance of 'std::runtime_error'
   what():  /u/user/src/picongpu/thirdParty/cupla/alpaka/include/alpaka/event/EventUniformCudaHipRt.hpp(175) 'ret = ALPAKA_API_PREFIX(EventQuery)(event.m_spEventImpl->m_UniformCudaHipEvent)' returned error  : 'cudaErrorIllegalAddress': 'an illegal memory access was encountered'!
 /ptmp/user/pig/runs/22-beam2dlehe/tbg/cpuNumaStarter.sh: line 90: 76272 Aborted                 numactl --cpunodebind="$useNumaNode" --preferred="$useNumaNode" $*
 srun: error: ravg1079: task 1: Exited with exit code 134
 srun: Terminating job step 759734.0
 slurmstepd: error: *** STEP 759734.0 ON ravg1079 CANCELLED AT 2021-10-04T08:42:41 ***
 srun: error: ravg1079: tasks 0,2-3: Terminated
 srun: Force Terminated job step 759734.0
```

I am using openPMD backend with ADIOS2.

Since I have adapted and modified the .tpl and picongpu.profile from the MPCDF cluster draco to raven myself, it might be that I have missed something. But otherwise I could run any simulations without any problems.

If I should also provide you with the .tpl, .profile and also the .cfg file, please let me know as they contain some account informations.

**Comment by sbastrakov** [comment] 2021-10-04 08:32
Hello @ervw12 , thanks for reporting. This seems unusual. Does it happen consistently? I do not think this is something really related to picongpu.profile or .tpl on your side. But in order to better replicate your setup and software versions, please provide it, and also .param files and .cfg file

@franzpoeschel do you think there is a chance RNG state seriazliation (using `char` internally) may be causing it? Iirc you also made some small change to openPMD writer about same time, but that was probably just a refactoring.

**Comment by ervw12** [comment] 2021-10-04 12:16
[gausbeam2d.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/7277908/gausbeam2d.zip)
Here is a zip folder including the run.cfg and raven-mpcdf/general.tpl and the picongpu.profile files. 

The problem happens consistently with each simulation I have set up so far.

**Comment by PrometheusPi** [comment] 2021-10-04 15:51
@ervw12 Thanks for reporting - very strange error indeed. What kind of GPUs are you using? 
@sbastrakov These restart problems with PIConGPU+ADIOS2 sound familiar to what I encountered with taurus ml.

**Comment by ervw12** [comment] 2021-10-04 16:31
@PrometheusPi The GPUs of the raven cluster have following properties:

- 192 GPU-accelerated nodes (each hosting 4 Nvidia A100 GPUs, interlinked with NVlink 3)
- GPU type: Nvidia A100 NVlink 40 GB HBM2, CUDA compute capability 8.0 / Ampere
- CPU host: Intel Xeon IceLake Platinum 8360Y with 72 CPU cores and 512 GB per node

Following the guide of mpcdf I am reserving 125GB of memory per node, 500GB if I am using one full node.

**Comment by sbastrakov** [comment] 2021-10-04 16:41
Thanks for the info @ervw12 . Unfortunately, I couldn't reproduce the issue, on our cluster it runs and loads from a checkpoint fine. In order to further investigate, could you build PIConGPU as follows:
`pic-build -c "-DPMACC_BLOCKING_KERNEL=ON -DCUPLA_STREAM_ASYNC_ENABLE=OFF -DPIC_VERBOSE=49"`
and use this version to try to load from a checkpoint. The checkpoints themselves could be from a normal build, these flags do not affect them. If should still crash as before, but will hopefully help to narrow down the place where it happens. Please attach the resulting stdout and stderr files.

**Comment by sbastrakov** [comment] 2021-10-04 16:42
Could it be our alignment is somehow not sufficient for Ampere @psychocoderHPC ?

**Comment by franzpoeschel** [comment] 2021-10-04 17:13
> @franzpoeschel do you think there is a chance RNG state seriazliation (using `char` internally) may be causing it? Iirc you also made some small change to openPMD writer about same time, but that was probably just a refactoring.

Loading chars in itself should not be a problem. Is the target buffer allocated as a char array or as an array of the datatype that you use for RNG later on? If you allocate it first as a char array and then just reinterpret_cast it as something else, this will cause issues.
I can have a more detailed look after my vacation this week.

**Comment by PrometheusPi** [comment] 2021-10-04 19:24
Thanks @ervw12 for the cluster details. They are sufficiently different (A100 vs. V100, Intel Xeon vs. Power) that this should not cause the error. I hope that the suggested increase in the verbose level and using blocking kernels as suggested by @sbastrakov will shed more light into this problem.

**Comment by ervw12** [comment] 2021-10-04 19:26
Here are the stderr and stdout files with higher verbose level. Strangely for a 2D run it has worked one time now to restart from checkpoint. But for a 3D simulation it gave the same error.
[output_error.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/7280721/output_error.zip)

**Comment by sbastrakov** [comment] 2021-10-04 19:27
Thanks @franzpoeschel .
I am loading into memory already allocated by the rng state buffed. So the pattern you mentioned shouldn't be there.

**Comment by sbastrakov** [comment] 2021-10-05 07:37
Thanks @ervw12 . Unfortunately, this didn't point out to the error origin as I hoped for. We see that rank 0 finished loading from the checkpoint and started computing afterwards, and almost immediately things went wrong. But it could be some other process was still loading.

 Here are some more things to hopefully help investigation:

- For even more diagnostic output build with `pic-build -c "-DPMACC_BLOCKING_KERNEL=ON -DCUPLA_STREAM_ASYNC_ENABLE=OFF -DPIC_VERBOSE=127 -DPMACC_VERBOSE=127"`
- Switch to the current `dev` branch of PIConGPU so that we surely have the same code base. Also produce checkpoints with the same version. (We just had a  bug with acceleration pusher compilation, but it's now fixed and merged) 
- You seem to be using the `dev` branch of openPMD API. Could you try the last release instead? This way we would eliminate the possibility that something got broken there or on PIConGPU side since the release.
- Could you try if the issue exists with 1 MPI process? If so, it would be preferable as then the output corresponds very well to what is happening.

**Comment by ervw12** [comment] 2021-10-05 08:29
How could I get the last release of openPMD API? On github the `dev` branch is the default one and I cannot find a "release" branch.

**Comment by sbastrakov** [comment] 2021-10-05 08:31
The releases are marked by tags. So just `git checkout 0.14.2`

**Comment by ervw12** [comment] 2021-10-05 09:34
So after switching openPMD to branch 0.14.2, pulling from the picongpu `dev` branch and recompiling, everything works fine now. For completeness the stdout and stderr files for a 1 MPI process run:
[output_files.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/7284551/output_files.zip)

A run on 2 GPUs also works fine. I will make some larger runs the following days but if nothing occurs, I would close the issue if you do not have any other things you would like to know.

Maybe you can also use the .tpl and picongpu.profile files I have sent before and add the raven-mpcdf cluster to your list as some colleagues of mine would be also interested in picongpu in near future.

**Comment by sbastrakov** [comment] 2021-10-05 09:42
Okay, so if there will be an issue again please compile with those flags, run with 1 rank and attach the output. We will test what doesn't work with the `dev` branch of openPMD API, I made a new issue for it #3846.

Regarding the profiles. Sure, we could add it. Would be even better if you made a pull request for it, since you authored those files and also can test the resulting setup. Is it fine with you?

**Comment by ervw12** [comment] 2021-10-05 09:51
Ok, I will report new issues to #3846 then.

Yes, thats fine with me. But that may take some days, since I have never made a pull request before.

**Comment by sbastrakov** [comment] 2021-10-05 10:27
Nice! We have a small [doc page on contributing](https://picongpu.readthedocs.io/en/latest/dev/CONTRIBUTING.html). BIn this case it should be quite straightforward: make your github fork of this repo, create a branch based on `dev`, add your profile files (the profile and tpl) to where the other profiles are, include them to the docs [here](https://raw.githubusercontent.com/ComputationalRadiationPhysics/picongpu/dev/docs/source/install/profile.rst), commit, push, and open a pull request. Feel free to ask for assistance if needed.

**Closed** 2021-11-11 15:00 UTC
Labels: bug, component: plugin
