### ISSUE TITLE
Automatically remove particles from PML zones

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#3032] opened 2019-08-22 11:49 UTC
@sbastrakov mentioned that when choosing the `YeePML` field solver, the boundary regions of the box need to be particle-free.

As of now, the user would be required to remove particles from the boundary layers by specifically setting this up in their density profile or removing the particles via a user-filter after creation.
However, having to do this manually is quite error-prone as you can still easily end up with particles in these areas when changing the overall box size in the `cfg` file and forgetting about the `param` files.

IMO, we should automate this so that the user can be blissfully ignorant about it.
We can leave a notification about the particle removal for a certain log-level and just mention in it our docs.

**Comment by sbastrakov** [comment] 2019-08-22 12:21
To add up a little bit and clarify my earlier points.

Having particles in the PML zone should not lead to crashes or bad things happening immediately. However, it causes some spurious charges and so potentially leads to unphysical behavior. In the absorber area, there is no good way to fully account for the currents created by particles. This is also true for the exponential damping absorber, which treats it differently from my PML implementation, but also incorrectly (again, I doubt there is a "correct" way in this context). So in this regard having parts of the target initially in the absorber area is not ideal for both absorbers.

The issue is not only with the target overlapping with the absorber - this can actually be solved on our side as suggested by @n01r or alternatively by providing proper instruments for a user to make a setup. In my opinion, the main issue is particle movement between the absorber and the main (internal) simulation areas, which generates a spurious charge on the PML-internal area boundary. Btw, just removing particles on this border also introduces such spurious charge. However, it should still be better than what we do now.

@n01r I understand your suggestion. I do not particularly like mixing processing of density profiles with PML parameters. However, I understand that now it is what a user has to do manually and then it is less bad to do it on our side instead. Maybe having some explicit notion of a boundary, like what we discussed in May, can be a better design. For example, a user specifies that a certain boundary is absorbing, and what methods and with which parameters to use for it, and then from this combination we find out where exactly the absorption happens and apply it accordingly. Then the target will be initialized in the whole area, but then the part in the PML would be cut off due to absorbing particle boundary conditions.

**Comment by sbastrakov** [comment] 2021-09-17 16:24
This is almost possible, just waits for #3776  to be reviewed and merged.

**Closed by sbastrakov** 2021-09-17 16:24 UTC
Labels: component: core
