### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by pordyna** [ComputationalRadiationPhysics/picongpu#4347] opened 2022-11-09 14:01 UTC
CI fails on all PRs, even when no code is changed (only comments), see #4346

It looks like it fails at
```bash
$ pyflakes $(ls -w 1 -d */ | grep -v thirdParty | tr "\n" " ")
test/python/__init__.py:2:1: 'from .picongpu import *' used; unable to detect undefined names
test/python/__init__.py:2:1: '.picongpu.*' imported but unused
test/python/picongpu/__init__.py:2:1: 'from .quick import *' used; unable to detect undefined names
test/python/picongpu/__init__.py:2:1: '.quick.*' imported but unused
test/python/picongpu/__init__.py:3:1: 'from .compiling import *' used; unable to detect undefined names
test/python/picongpu/__init__.py:3:1: '.compiling.*' imported but unused
[...]
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```
Could be maybe related to #4091? @BrianMarre @PrometheusPi @psychocoderHPC

**Comment by BrianMarre** [comment] 2022-11-09 14:08
the CI pyflake call is wrong,
it should be:
```
pyflakes $(ls -d */ | grep -Ev "thirdParty|test") $(find test/ | grep "\.py$" | grep -Ev "__init__.py|__main__.py")
```

**Comment by BrianMarre** [comment] 2022-11-09 14:10
So yes indirectly it is related, as in for some reason the exclusion of the tests was reverted causing the original problem to resurface.

**Comment by BrianMarre** [comment] 2022-11-09 14:16
but the [CI-yaml](https://github.com/ComputationalRadiationPhysics/picongpu/blob/01de703aced8e87d5f8945dc886b93ebf948660c/.gitlab-ci.yml#L43-L46) is still correct?

**Comment by PrometheusPi** [comment] 2022-11-09 14:47
The issue seems to be recent but it is not obvious why.

In resent CI runs (last week), the CI executed:
```bash
pyflakes $(ls -d */ | grep -Ev "thirdParty|test") $(find test/ | grep "\.py$" | grep -Ev "__init__.py|__main__.py")
```
but now it executes:
```bash
pyflakes $(ls -w 1 -d */ | grep -v thirdParty | tr "\n" " ")
```

which of course triggers all errors. 

The versions installed are all the same:
old:
![grafik](https://user-images.githubusercontent.com/5121158/200860912-0765019d-e4c5-4c7d-8b3e-c25a212aebf7.png)

new:
![grafik](https://user-images.githubusercontent.com/5121158/200861016-0f184849-2280-4aae-bebe-cf7493ed374b.png)

A `git diff` on `./.gitlab-ci.yml` shows no change since 16622dd773b5926bc5a7aea0925ae7657b5641fe end of August.

**Comment by psychocoderHPC** [comment] 2022-11-09 15:00
The PR used an old base branch therefore the CI failed.
https://github.com/ComputationalRadiationPhysics/picongpu/pull/4346#issuecomment-1308872133

I close the issue, the PR needs only a rebase.

**Closed as completed by psychocoderHPC** 2022-11-09 15:00 UTC

**Comment by PrometheusPi** [comment] 2022-11-09 15:15
@psychocoderHPC I thought the CI takes the `dev` branch, then adds the changes of the pull request and then executes the CI. But it looks like it just takes the pull request version and then runs the CI. 

I would consider this a pitfall since we thus only check old code and not as the code will be in the `dev` branch after merging.

**Comment by psychocoderHPC** [comment] 2022-11-09 15:57
> I thought the CI takes the dev branch, then adds the changes of the pull request, and then executes the CI.

This is how it should be best but not easy to do.

> But it looks like it just takes the pull request version and then runs the CI.

This is the default behavior with any CI. The problem is that you do not know against which dev branch version you should rebase best.
