### ISSUE TITLE
CUDA 11 Support: Alpaka Concept Build error (w/ GCC 8.3.0)

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#3349] opened 2020-09-14 17:36 UTC
Hi,

I am trying to build PIConGPU 0.5.0 from the Spack recipes (this commit: [5b60962469014a89f1308c633cbf0e9f68d2ca9e](https://github.com/ComputationalRadiationPhysics/spack-repo/commit/5b60962469014a89f1308c633cbf0e9f68d2ca9e)).

Running
```bash
spack load -r picongpu
pic-create $PIC_EXAMPLES/LaserWakefield $HOME/picInputs/lwfa-test-0.5.0
cd  $HOME/picInputs/lwfa-test-0.5.0
pic-build
```

fails with a compile-error.

Details from `cd .build && make VERBOSE=ON`:
```
-- Generating /home/axel/picInputs/lwfa-test-0.5.0/.build/CMakeFiles/cupla.dir/__/__/thirdParty/cupla/src/./cupla_generated_stream.cpp.o
/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/cuda-11.0.2-djlgc4nuxbftxzz2gesle7dugja5n7lp/bin/nvcc /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/thirdParty/cupla/src/stream.cpp -x=cu -c -o /home/axel/picInputs/lwfa-test-0.5.0/.build/CMakeFiles/cupla.dir/__/__/thirdParty/cupla/src/./cupla_generated_stream.cpp.o -ccbin /usr/bin/g++-8 -m64 -DALPAKA_ACC_GPU_CUDA_ONLY_MODE -DALPAKA_ACC_GPU_CUDA_ENABLED -DALPAKA_DEBUG=0 -DCUPLA_STREAM_ASYNC_ENABLED=1 -DBOOST_RESULT_OF_USE_TR1_WITH_DECLTYPE_FALLBACK -DBOOST_NO_AUTO_PTR -DPMACC_VERBOSE_LVL=0 -DPIC_VERBOSE_LVL=1 -DCMAKE_VERSION=3.18.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM=Linux-5.4.0-42-generic -DCMAKE_SYSTEM_PROCESSOR=x86_64 -DCMAKE_CXX_COMPILER_ID=GNU -DCMAKE_CXX_COMPILER_VERSION=8.4.0 -DENABLE_HDF5=1 -DPIC_ENABLE_PNG=1 -DBOOST_ALL_NO_LIB -Xcompiler ,\"-O3\",\"-DNDEBUG\" --expt-extended-lambda --expt-relaxed-constexpr --generate-code arch=compute_35,code=sm_35 --generate-code arch=compute_35,code=compute_35 -std=c++11 --use_fast_math --ftz=false -Xcudafe --display_error_number -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -DNVCC -I/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/cuda-11.0.2-djlgc4nuxbftxzz2gesle7dugja5n7lp/include -I/home/axel/picInputs/lwfa-test-0.5.0/include -I/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/thirdParty/alpaka/include -I/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/thirdParty/cupla/include -I/usr/include/mpich -I/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/openmpi-3.1.6-wrnxwfpzowztl3xfmjurk6mf3ce2hnpu/include -I/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/thirdParty/mallocMC/src/include -I/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/include/pmacc/.. -I/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/include/picongpu/.. -I/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/include
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/thirdParty/alpaka/include/alpaka/core/Concepts.hpp:81:33: error: ‘__T0’ was not declared in this scope
                 static_assert(std::is_base_of<type, TDerived>::value, "The type implementing the concept has to be a publicly accessible base class!");
                                 ^~~~
/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/thirdParty/alpaka/include/alpaka/core/Concepts.hpp:81:33: note: suggested alternative: ‘__y0’
                 static_assert(std::is_base_of<type, TDerived>::value, "The type implementing the concept has to be a publicly accessible base class!");
                                 ^~~~
                                 __y0
/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/thirdParty/alpaka/include/alpaka/core/Concepts.hpp:81:47: error: template argument 1 is invalid
                 static_assert(std::is_base_of<type, TDerived>::value, "The type implementing the concept has to be a publicly accessible base class!");
                                               ^
-- Removing /home/axel/picInputs/lwfa-test-0.5.0/.build/CMakeFiles/cupla.dir/__/__/thirdParty/cupla/src/./cupla_generated_stream.cpp.o
/usr/bin/cmake -E rm -f /home/axel/picInputs/lwfa-test-0.5.0/.build/CMakeFiles/cupla.dir/__/__/thirdParty/cupla/src/./cupla_generated_stream.cpp.o
CMake Error at cupla_generated_stream.cpp.o.Release.cmake:280 (message):
  Error generating file
  /home/axel/picInputs/lwfa-test-0.5.0/.build/CMakeFiles/cupla.dir/__/__/thirdParty/cupla/src/./cupla_generated_stream.cpp.o
```

## CMake Output

```
$ pic-build 
build directory: .build
cmake command: cmake  -DCMAKE_INSTALL_PREFIX=.. -DPIC_EXTENSION_PATH=..   -DALPAKA_ACC_GPU_CUDA_ENABLE=ON -DALPAKA_ACC_GPU_CUDA_ONLY_MODE=ON /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/include/picongpu
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc-8 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-8 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost 1.70.0 at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET
-- Found boost_headers 1.70.0 at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/boost_headers-1.70.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/cuda-11.0.2-djlgc4nuxbftxzz2gesle7dugja5n7lp (found suitable version "11.0", minimum required is "8.0") 
-- ALPAKA_ACC_GPU_CUDA_ONLY_MODE
-- ALPAKA_ACC_GPU_CUDA_ENABLED
-- Found alpaka: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/thirdParty/alpaka/include (found version "0.4.0") 
-- _cupla_COMPILE_OPTIONS_PUBLIC: -Wall;-Wextra;-Wno-unknown-pragmas;-Wno-unused-parameter;-Wno-unused-local-typedefs;-Wno-attributes;-Wno-reorder;-Wno-sign-compare
-- _cupla_COMPILE_DEFINITIONS_PUBLIC: ALPAKA_ACC_GPU_CUDA_ONLY_MODE;ALPAKA_ACC_GPU_CUDA_ENABLED;ALPAKA_DEBUG=0;CUPLA_STREAM_ASYNC_ENABLED=1
-- _cupla_INCLUDE_DIRECTORIES_PUBLIC: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/cuda-11.0.2-djlgc4nuxbftxzz2gesle7dugja5n7lp/include;/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/thirdParty/alpaka/include;/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/thirdParty/cupla/include
-- _cupla_LINK_LIBRARIES_PUBLIC: general;pthread;general;rt;Boost::boost;general;/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/cuda-11.0.2-djlgc4nuxbftxzz2gesle7dugja5n7lp/lib64/libcudart.so
-- Found cupla: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/thirdParty/cupla/include (found version "0.2.0") 
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/libmpich.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/libmpichcxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found Boost 1.70.0 at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS filesystem;system;math_tr1
-- Found boost_filesystem 1.70.0 at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/boost_filesystem-1.70.0
--   libboost_filesystem.a
-- Adding boost_filesystem dependencies: headers
-- Found boost_system 1.70.0 at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/boost_system-1.70.0
--   libboost_system.a
-- Adding boost_system dependencies: headers
-- Found boost_math_tr1 1.70.0 at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/boost_math_tr1-1.70.0
--   libboost_math_tr1.a
-- Adding boost_math_tr1 dependencies: headers
-- Found Boost: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found suitable version "1.70.0", minimum required is "1.65.1") found components: filesystem system math_tr1 
-- Boost: result_of with TR1 style and decltype fallback
-- Boost: deactivate std::auto_ptr
CMake Warning at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/include/pmacc/PMaccConfig.cmake:353 (message):
  Untested CUDA release >10.2 (Found 11.0)! Maybe use a newer PIConGPU?
Call Stack (most recent call first):
  CMakeLists.txt:95 (find_package)


-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found CUDA: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/cuda-11.0.2-djlgc4nuxbftxzz2gesle7dugja5n7lp (found suitable version "11.0", minimum required is "5.0") 
-- Found Boost 1.70.0 at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED
-- Found Boost: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found suitable version "1.70.0", minimum required is "1.48.0")  
-- Using mallocMC from thirdParty/ directory
-- Found Boost 1.70.0 at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED
-- Found mallocMC: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/thirdParty/mallocMC/src (found suitable version "2.3.1", minimum required is "2.3.0")  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found Boost 1.70.0 at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED
-- Found ZLIB: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/zlib-1.2.11-xz7vmkd54yh54wvnhf7o4fjft6h6f2rv/lib/libz.so (found version "1.2.11") 
-- Found Boost 1.70.0 at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS program_options;filesystem;system;math_tr1;serialization
-- Found boost_program_options 1.70.0 at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/boost_program_options-1.70.0
--   libboost_program_options.a
-- Adding boost_program_options dependencies: headers
-- Found boost_serialization 1.70.0 at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/boost_serialization-1.70.0
--   libboost_serialization.a
-- Adding boost_serialization dependencies: headers
-- Found Boost: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found suitable version "1.70.0", minimum required is "1.65.1") found components: program_options filesystem system math_tr1 serialization 
-- Found CUDA: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/cuda-11.0.2-djlgc4nuxbftxzz2gesle7dugja5n7lp (found version "11.0") 
-- Found NVML: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so  
CMake Warning (dev) at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/picongpu-0.5.0-tvwzc3qnkltl6cdd26wn7gmrizke4xtg/thirdParty/cuda_memtest/CMakeLists.txt:127 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "cuda_memtest".  All uses of target_link_libraries with a target
  should be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * /usr/share/cmake-3.18/Modules/FindCUDA.cmake:1901 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Boost 1.70.0 at /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS program_options
-- Found Boost: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/boost-1.70.0-5dqbl4whn6qyh3g56f2cmi52u3t4st3y/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found suitable version "1.70.0", minimum required is "1.65.1") found components: program_options 
-- Can NOT find 'adios_config' - set ADIOS_ROOT, ADIOS_DIR or INSTALL_PREFIX, or check your PATH
-- Could NOT find ADIOS (missing: ADIOS_LIBRARIES ADIOS_INCLUDE_DIRS) (Required is at least version "1.13.1")
-- Found HDF5: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/hdf5-1.10.6-xwxigveaapjnrb47q6dkjt3geckdnpcn/lib/libhdf5.so;/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/zlib-1.2.11-xz7vmkd54yh54wvnhf7o4fjft6h6f2rv/lib/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.6")  
-- Found Splash: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/libsplash-1.7.0-dyvrf5lykaie2cs2qqey2zc7kx4i7spt/lib/cmake/Splash
-- Found PNG: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/libpng-1.6.37-2pxjyt4kauckqhhip5dkttlohpaubl55/lib/libpng.so (found version "1.6.37") 
-- Found Freetype: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/freetype-2.10.1-mpvuw7st5civd3a4iyp5afrxmah32hk5/lib/libfreetype.so (found version "2.10.1") 
-- Found PNGwriter: /home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/pngwriter-0.7.0-gctlplbshzklk54x27vkgripo34ezoed/lib/cmake/PNGwriter
-- Could NOT find ISAAC - set ISAAC_DIR or check your CMAKE_PREFIX_PATH
-- Configuring done
-- Generating done
-- Build files have been written to: /home/axel/picInputs/lwfa-test-0.5.0/.build
```

## OS

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

### Dependencies
```
$ spack spec picongpu
Input spec
--------------------------------
picongpu

Concretized
--------------------------------
picongpu@0.5.0%gcc@8.4.0~adios+hdf5~isaac+png backend=cuda cudacxx=nvcc arch=linux-ubuntu18.04-skylake
    ^boost@1.70.0%gcc@8.4.0+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=11 visibility=hidden arch=linux-ubuntu18.04-skylake
        ^bzip2@1.0.8%gcc@8.4.0+shared arch=linux-ubuntu18.04-skylake
            ^diffutils@3.7%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
                ^libiconv@1.16%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
        ^zlib@1.2.11%gcc@8.4.0+optimize+pic+shared arch=linux-ubuntu18.04-skylake
    ^cmake@3.18.1%gcc@8.4.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu18.04-skylake
    ^cuda@11.0.2%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
        ^libxml2@2.9.10%gcc@8.4.0~python arch=linux-ubuntu18.04-skylake
            ^pkg-config@0.29.1%gcc@8.4.0+internal_glib patches=49ffcd644e190dc5efcb2fab491177811ea746c1a526f75d77118c2706574358 arch=linux-ubuntu18.04-skylake
            ^xz@5.2.5%gcc@8.4.0~pic arch=linux-ubuntu18.04-skylake
    ^libsplash@1.7.0%gcc@8.4.0+mpi build_type=RelWithDebInfo patches=669608721dfce0ada7cef1ac84344352791a8916b7bb98ca8a0d4e6d4670e744 arch=linux-ubuntu18.04-skylake
        ^hdf5@1.10.6%gcc@8.4.0~cxx~debug~fortran~hl~java+mpi+pic+shared~szip~threadsafe api=none arch=linux-ubuntu18.04-skylake
            ^openmpi@3.1.6%gcc@8.4.0~atomics~cuda~cxx~cxx_exceptions+gpfs~java~legacylaunchers~lustre~memchecker~pmi~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=none schedulers=none arch=linux-ubuntu18.04-skylake
                ^hwloc@1.11.11%gcc@8.4.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml+pci+shared arch=linux-ubuntu18.04-skylake
                    ^libpciaccess@0.16%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
                        ^libtool@2.4.6%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
                            ^m4@1.4.18%gcc@8.4.0+sigsegv patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 arch=linux-ubuntu18.04-skylake
                        ^util-macros@1.19.1%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
                    ^numactl@2.0.12%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
                        ^autoconf@2.69%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
                        ^automake@1.15.1%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
    ^pngwriter@0.7.0%gcc@8.4.0 build_type=RelWithDebInfo arch=linux-ubuntu18.04-skylake
        ^freetype@2.10.1%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
            ^libpng@1.6.37%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
    ^rsync@3.2.2%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
        ^lz4@1.9.2%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
        ^openssl@1.1.1%gcc@8.4.0+systemcerts arch=linux-ubuntu18.04-skylake
        ^popt@1.16%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
        ^xxhash@0.7.4%gcc@8.4.0 arch=linux-ubuntu18.04-skylake
        ^zstd@1.4.5%gcc@8.4.0+pic arch=linux-ubuntu18.04-skylake
```

**Comment by psychocoderHPC** [comment] 2020-09-14 18:05
PIConGPU 0.5.0 is not supporting CUDA 11. See CMake output `Untested CUDA release >10.2 (Found 11.0)! Maybe use a newer PIConGPU?`

The strange point is that the compile error os pointing to the namespace `std`

**Comment by psychocoderHPC** [comment] 2020-09-14 18:05
I will check if I can reproduce the issue and if it is possible to workaround.

**Comment by ax3l** [comment] 2020-09-22 19:22
> PIConGPU 0.5.0 is not supporting CUDA 11.

Oh right, let's track this for CUDA 11 progress then.

> I will check if I can reproduce the issue and if it is possible to workaround.

Thanks!

I updated the supported version ranges of dependencies here (3 PRs currently):
https://github.com/ComputationalRadiationPhysics/spack-repo/pulls

**Comment by BrianMarre** [comment] 2024-03-12 13:54
@psychocoderHPC since CUDA 11 is supported by the current dev and the last release could we close this issue?

**Closed** 2024-06-17 07:47 UTC
Labels: component: third party, backend: cuda, install
