### ISSUE TITLE
Problem to run TNSA simulation on multiple node

### ISSUE THREAD

**Issue by denisbertini** [ComputationalRadiationPhysics/picongpu#4109] opened 2022-05-16 10:47 UTC
Trying to run  TNSA simulation (param files attached) using `picongpu` on more than one node gives immediately
the following MPI related error:
 ```
Unhandled exception of type 'St16invalid_argument' with message 'wrong parameters or wrong mpirun-call!', terminating

```
Any idea what could trigger such type of error?

This error for example does not show up when running the LWFA simulation from the `picongpu` examples.

[tnsa.param.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8699335/tnsa.param.tar.gz)

**Comment by sbastrakov** [comment] 2022-05-16 11:07
Hello @denisbertini ,

Normally, this error message means that the `-d` argument of PIConGPU does not match the number of MPI processes actually launched. That could happen if your `mpirun/mpiexec` call is somehow wrong, or your SLURM and MPI are not properly connected to one another (or it requires a certain workflow that isn't followed). Ultimately, the issue is almost always in a `.tpl` file used.

In order to investigate, could you also attach the following:

- `.profile` and `.tpl` files used for this failing run
- `.cfg` file used for this failing run
- Same files for the LWFA run that succeded.

**Comment by denisbertini** [comment] 2022-05-16 11:17
Hi @sbastrakov 
I attached the relevant files that i use for TNSA and LWFA ( working example) 
[cfg.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8699548/cfg.tar.gz)

**Comment by sbastrakov** [comment] 2022-05-16 11:26
Thanks @denisbertini ,

Sorry, I forgot to ask initially. What is the number of devices you are (or want to) use in these cases?
From your `.tpl` file it appears to me that it is only for 1-process runs since you never launch with `mpiexec/mpirun`. Compare e.g. to [this line](https://github.com/ComputationalRadiationPhysics/picongpu/blob/d9ab3532a2b0d10e752b5b701ec14254f486d176/etc/picongpu/hemera-hzdr/gpu.tpl#L116) . So i believe an equivalent of our `mpiexec -np !TBG_tasks ` is missing in your script. Sorry if i misunderstood something.

**Comment by sbastrakov** [comment] 2022-05-16 11:29
I think a safest way to see what is actually getting launched, is to attach `tbg` subdirectory inside your output directory.

**Comment by denisbertini** [comment] 2022-05-16 11:40
@sbastrakov  i am not usin `mpirun/mpiexec` but `srun` to launch the processes and for the `LWFA` simulation case it is working
as expected.
The TNSA  example i sent works for `n-devices<=8` ( one node has up to 8 GPU devices) but as soon i i want to run with lets say the double (`16.cfg`) than i have this error poping up and the processes terminate immediately

**Comment by denisbertini** [comment] 2022-05-16 11:53
I attach now the `tbg` subdirectory from the output directories for both TNSA and LWFA
[tbg_lwfa.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8699750/tbg_lwfa.tar.gz)
[tbg_tnsa.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8699751/tbg_tnsa.tar.gz)

**Comment by sbastrakov** [comment] 2022-05-16 12:16
Why is your `--cpus-per-task` different between the two attached runs - 6 for TNSA and 12 for LWFA (in `submit.start`)? That hints at different versions of `.tpl` file used, or maybe some other unaccounted differences between the runs. I suggest sticking to the LWFA version of `.tpl` for now since it seems to work.

Since you have LWFA running with 16 GPUs and `-d 2 4 2` let's start from there. Please check if it runs consistently, e.g. if you make a few identical runs in a row, are all of them fine? Does it also work on other process topologies e.g. `-d 8 2 1` and `-d 1 2 8`?

Then, there should really be no MPI-related difference between the setups once you use same number and configuration of ranks. So if you run the TNSA build of PIConGPU with exactly same parameters that work for LWFA, it should also run. It would be very odd if it didn't. From your attached results, other things were also different (number of nodes, `--cpus-per-task`), for now we should eliminate the differences while investigating.

**Comment by psychocoderHPC** [comment] 2022-05-16 12:19
As @sbastrakov pointed out I also think that there is a mismatch between the number of tasks started by the batch syste mand what you use in `-d` could you change your tpl file and substitude

```
srun -K1 singularity exec --bind /cvmfs --rocm ./pic_sub.sh
```

to

```
srun -K1 singularity exec --bind /cvmfs --rocm hostname
```

And post your result. The number of host names shown should be 32 in your example.

**Comment by denisbertini** [comment] 2022-05-16 13:30
@psychocoderHPC 
Made the change you suggested, on the TNSA config,  the output is 
```
Running program...
lxbk1086
lxbk1086
lxbk1086
lxbk1086
lxbk1086
lxbk1086
lxbk1086
lxbk1086
lxbk1121
lxbk1121
lxbk1121
lxbk1121
lxbk1121
lxbk1121
lxbk1121
lxbk1121
```  

as expected 8 processes / node are initiated and 2 different nodes are selected.

**Comment by denisbertini** [comment] 2022-05-16 13:36
i used the `16.cfg` to get this result

**Comment by psychocoderHPC** [comment] 2022-05-16 14:56
But the file [tbg_tnsa.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8699751/tbg_tnsa.tar.gz) is showing

```
#SBATCH --partition=gpu
#SBATCH --time=2:00:00
#SBATCH --job-name=lwfa_016
#SBATCH --nodes=4                           # Nb of nodes
#SBATCH --ntasks=32                          # Nb of MPI tasks
#SBATCH --gres=gpu:8
#SBATCH --cpus-per-task=6           # CPU Cores per MPI process
```

`--ntasks` is set to 32, and not 16 and the picongpu command is configured to use 32 GPUs too

```
/lustre/rz/dbertini/gpu/data/lwfa_016/input/bin/picongpu  --author "dbertini" -d 4 4 2 ...
```

Your `cfg` file is showing 32 tasks too, but from the job name it point that it should be a 16 GPU run.

```
TBG_devices_x=4
TBG_devices_y=4
TBG_devices_z=2
```

**Comment by denisbertini** [comment] 2022-05-16 15:51
May be the files i sent are incorrect.
I just checked the `submit.start` file in the `tbg` directory output of the test program and it shows
```
#SBATCH --partition=gpu
#SBATCH --time=2:00:00
#SBATCH --job-name=lwfa_001
#SBATCH --nodes=2                           # Nb of nodes
#SBATCH --ntasks=16                          # Nb of MPI tasks
#SBATCH --gres=gpu:8
#SBATCH --cpus-per-task=12           # CPU Cores per MPI process
#SBATCH --mem=0                                   # Requested Total Job Memory / Node  
#SBATCH --mem-per-gpu=64000000
#SBATCH --gpu-bind=closest 
#SBATCH --mail-type=NONE
#SBATCH --mail-user=d.bertini@gsi.de
#SBATCH --chdir=/lustre/rz/dbertini/gpu/data/lwfa_001
#SBATCH -o pog_%j.out
#SBATCH -e pog_%j.err

```
which is then consistent with the previous output

**Comment by denisbertini** [comment] 2022-05-16 16:03
i reproduce the problem with the same config. I attach the tar file corresponding to the failed TNSA run.
The config is `16.cfg` that is copied to `submit.cfg` in the output `tbg` directory.

[tbg_tnsa_16cfg.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8701593/tbg_tnsa_16cfg.tar.gz)

**Comment by psychocoderHPC** [comment] 2022-05-17 12:12
Here is a part of your `submit.start` file

```bash
## MPI
export OMPI_MCA_io=^ompio
export OMPI_MCA_mpi_leave_pinned=0
export OMPI_MCA_mpi_leave_pinned=0
export OMPI_MCA_btl_openib_allow_ib=1
export OMPI_MCA_btl_openib_rdma_pipeline_send_length=100000000
export OMPI_MCA_btl_openib_rdma_pipeline_frag_size=100000000

/lustre/rz/dbertini/gpu/data/lwfa_002/input/bin/picongpu  --author "dbertini" -d 2 4 2                    -g 192 1024 192                      -s 4000                         -m --windowMovePoint 0.9                     --e_png.period 10 --e_png.axis yx --e_png.slicePoint 0.5 --e_png.folder pngElectronsYX                                 --e_png.period 10 --e_png.axis yz --e_png.slicePoint 0.5 --e_png.folder pngElectronsYZ                                 --e_macroParticlesCount.period 100                          --versionOnce

EOF
chmod +x /lustre/rz/dbertini/gpu/data/lwfa_002/tbg/pic_sub.sh 


if [ $? -eq 0 ] ; then
    # Run PIConGPU from within the singularity container ?
    srun -K1 singularity exec --bind /cvmfs --rocm $WORKDIR/sifs/picongpu.sif  /lustre/rz/dbertini/gpu/data/lwfa_002/tbg/pic_sub.sh
    #srun -K1 singularity exec --bind /cvmfs --rocm $WORKDIR/sifs/picongpu.sif  hostname
fi   
```

I do not know why you have content after `EOF` and if this is executed, I assume not. But the reason why you see the error message is that `/lustre/rz/dbertini/gpu/data/lwfa_002/input/bin/picongpu  ...` is not starting with `srun`. Therefore you executed PIConGPU not in an MPI context. `-d 2 4 2` said to PICoNGPU that where will be 16 MPI processes.

So change in your `tpl` file

```
!TBG_dstPath/input/bin/picongpu  !TBG_author !TBG_programParams
```
to
```
srun -K1 !TBG_dstPath/input/bin/picongpu  !TBG_author !TBG_programParams
```

**Comment by denisbertini** [comment] 2022-05-17 12:25
humm the `slurm` command are defined on the host and not inside the container,
`srun` is then used before the call to `singularity exec` which create a container context.
I used the same calls for `LWFA` and it works, it should also works for other example as well or i miss something here?

**Comment by sbastrakov** [comment] 2022-05-17 12:28
@denisbertini it seems you have an errorneous "bare" call to PIConGPU before you call it with `srun`. And that first call is incorrect and produces the error you see as then PIConGPU gets an MPI communicator with a single process, but its command line parameters say 16 processes. I mean the call just after `export` part in what @psychocoderHPC wrote.

We are not sure why the first call happens, it could be that there is an issue in your script file being generated, or maybe somehow our tool `tbg` does something wrong with substituting. But that contents of `submit.start` is what's actually executed.

**Comment by sbastrakov** [comment] 2022-05-17 12:33
I think to investigate and not get bothered with potential  `tbg` issues, perhaps it's easiser to move the wrapper script `pic_sub.sh` away as a standalone file, hardcoding stuff there when necessary.

**Comment by denisbertini** [comment] 2022-05-17 12:42
I checked that i got a  proper MPI environment inside the container with a MPI program just dumpng the rank of MPI processes:
```
Running program...
MPI process 5 of 8
MPI process 0 of 8
MPI process 2 of 8
MPI process 3 of 8
MPI process 7 of 8
MPI process 1 of 8
MPI process 4 of 8
MPI process 6 of 8
```

**Comment by denisbertini** [comment] 2022-05-17 12:44
without calling `srun` from inside the generated script

**Comment by denisbertini** [comment] 2022-05-17 13:11
I made the following tests which could may be help finding out what is going on.
I remove all `tbg` dependencies and try to run `picongpu` from an interactive session.
So i open a session with

```
srun -p gpu  --gres=gpu:8 --nodes=1  --ntasks-per-node=8  --pty bash -l

```
on just one node.
Then i execute the singularity container  and within the container execute manually the `picongpu` executable with `mpirun` command .
- Using TNSA compiled `picongpu` i get immediately the known error: 
```
Unhandled exception of type 'St16invalid_argument' with message 'wrong parameters or wrong mpirun-call!', terminating

```
- Using LWFA compiled` picongpu ` it works fine

This behaviour is then linked to the particular TNSA compiled `picongpu` exec

**Comment by sbastrakov** [comment] 2022-05-17 13:15
That's a great test!

I still do no understand why could it behave differently. To maybe look a bit more into that, could you make a new fresh setup + build of PIConGPU for these 2 examples from same environment. This is to exclude that your LWFA and TNSA builds were done with different MPI or something like that.

**Comment by denisbertini** [comment] 2022-05-17 16:03
OK good point, i will recompile the whole example again.

**Comment by denisbertini** [comment] 2022-05-19 12:32
OK you can close this issue, it was a trivial mistake from my part i.e mismatch in the `DIM` of the simulation.
After corrections ... all works fine !
Sorry for the noise !
And thanks for the constant great support !

**Comment by sbastrakov** [comment] 2022-05-19 12:37
Glad it works now!

Do you mean that PIConGPU was built for a 2d case and then launched e.g. with 16 processes with `-d 2 4 2`, and that caused the issue? If so, we probably can add a check and so a more explicit error message for that case.

**Comment by sbastrakov** [comment] 2022-05-19 12:39
I will have a look at how this is checked and try to add a more useful error reporting there.

**Comment by denisbertini** [comment] 2022-05-19 14:05
> Glad it works now!
> 
> Do you mean that PIConGPU was built for a 2d case and then launched e.g. with 16 processes with `-d 2 4 2`, and that caused the issue? If so, we probably can add a check and so a more explicit error message for that case.

Yes that was the trivial problem !

**Comment by sbastrakov** [comment] 2022-05-20 07:44
We will improve clarity of error messages in such a case, I made a new issue for that. Closing this one. Feel free to reopen if further help is needed here, or make new github issues for other questions or problems

**Closed as completed by sbastrakov** 2022-05-20 07:44 UTC
Labels: question
