### ISSUE TITLE
0.6 vs 0.7/dev

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu#4555] opened 2023-05-06 18:22 UTC
Hi all,

I saw that `v0.7` is right around the corner, is the `dev` branch stable enough for production use at the present time? 

Also, I noticed the latest version of the docs only mentions installation from source, is `spack` no longer supported?

In summary, what is the recommended version and install method right now?

**Comment by BrianMarre** [comment] 2023-05-08 10:42
1.) The dev branch is stable enough for simulations, but whether it is stable enough for production depends on your definition of production.

2.) Yes direct installation of PIConGPU via spack is no longer supported, but you may still use spack for installing dependencies

3.) the by me personally recommended path to a functioning install is now using spack to install the dependencies of picongpu and cloning picongpu by hand, for example see `etc/picongpu/bash-devServer-hzdr` for examples scripts and accompanying profiles.

**Comment by berceanu** [comment] 2023-05-08 12:15
Hi @BrianMarre thanks for the prompt reply. Let me give that installation script a try and get back to you.

Production in this context means large scale runs on hundreds of GPUs, using also the radiation plugin and the QED module. So stability is important, but so is corectness of output results.

**Comment by psychocoderHPC** [comment] 2023-05-08 15:23
From the stability, IMO dev is ahead of 0.6.0, we only observe some compile issues on OpenPower with nvcc 11.0.

**Comment by berceanu** [comment] 2023-05-08 15:26
I'm also excited about PyPIConGPU, that is included in dev already, right?

**Comment by BrianMarre** [comment] 2023-05-09 13:00
yes PyPIConGPU is included in the dev, but be aware that it still is quite limited due to  standard and implementation backlogs.
It might be that some features you need require you to hard code them into custom templates, see [here](https://picongpu.readthedocs.io/en/latest/usage/picmi/custom_template.html) for more information.

Also be sure to call `pip install -r requirements.txt` in the PIConGPU repository at least once.

If you encounter any problems, errors, have questions or need something, ask me. I am the maintainer for PyPIConGPU and ever grateful for feedback ;)

**Comment by BrianMarre** [comment] 2023-05-11 10:44
@berceanu any further questions? If not please remember to close the issue ;)

**Comment by berceanu** [comment] 2023-05-12 17:33
No further questions for now, will reopen if necessary. Thank you!

**Comment by berceanu** [comment] 2023-05-16 08:12
Sorry for reopening, just noticed that the **Synchrotron radiation extension** was removed some time ago via this [PR](https://github.com/ComputationalRadiationPhysics/picongpu/pull/4395). Since this is something we were actively using, I am curious to know if there are any plans atm to reimplement it in `0.7/dev`?

**Comment by PrometheusPi** [comment] 2023-05-22 08:58
@berceanu We had to remove the old synchrotron and bremsstrahlung radiation extension because it used the outdated parallelization method custl, and we did not have the manpower to adjust these extensions. 

From our side, there is no one planing to reimplement it soon (for 0.7.0). We however see, that many people seem to use these extensions, which we were not aware of. (Internally, both extensions are not used.) 
We are thus open to any pull request that adds these extensions without using custl.

**Comment by BrianMarre** [comment] 2023-06-26 10:54
@berceanu has your question been answered by PrometheusPi? If yes, please remember to close the issue again. ;)

**Closed as completed** 2023-06-26 16:00 UTC
Labels: question

**Comment by cbontoiu** [comment] 2023-08-02 01:30
Hi,
Does the latest dev version work with gcc 12?
Thank you.

**Comment by BrianMarre** [comment] 2023-08-02 10:52
yes it should and I can confirm that the current dev works with gcc 12 on cpu, but I did not try gcc on gpu's yet and the CI isn't testing gcc 12 yet, see Issue #4622. 

Summary: should work fine, but i you want to be sure stick to gcc 10, until we update the CI
