### ISSUE TITLE
General move preference for particles

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/picongpu#1555] opened 2016-08-23 13:01 UTC
The current definition of the incell-position causes a general preference or drift for particles to the "higher" direction. So moving particles with direction `(0 e 0)` or `(0 -e 0)` will not move them the same way.
Best example to showcase this: `e = 2^-24`, a value just below the machine epsilon (`1+e=1`)

Moving this particle 1024 times with `(0 e 0)` will result in a position of `0 2^-14 0`  but moving it in the opposite direction will leave its position at `(0 0 0)` due to the new cell assignment that basically does: `-2^-24 + 1 => 1 =>(incell invariant violated, moving it back to 0) => 0

For the best precision the incell position should be relative to the center and hence either `(-1, 1]` or `(-0.5, 0.5)`

@ax3l: Something like this could be the reason for the asymmetry in the intensity distribution you analysed, although I did not check that further.

**Comment by ax3l** [comment] 2016-08-23 13:31
@Flamefire thank you for the report! we are indeed aware of the subtleties of the in-cell definition of [0:1) vs [-0.5:0.5) and discussed this in the past. Nevertheless, our tests did not show relevant influence on physical values (e.g., the influence on sub-normal numbers near 0 is not affecting it).

Can you remind me what `asymmetry in the intensity distribution` you mean? I can't remember the setup you refer to. You mean in xrt?

**Comment by Flamefire** [comment] 2016-08-23 14:26
Ah, ok so this is probably a duplicate.
Well this is not really about subnormals (they are < 2^-126), but that particles moving with small angles are moving more in one direction than the other. It is possible, that the effect on the "pure" PIC algorithms is negligible, as there might be other errors dominant.
But I'm currently investigating this for xrt where this might be an issue (yes I meant that)

**Comment by ax3l** [comment] 2016-08-23 14:42
ok cool.

yes, so let us close that as duplicate of #208 and discuss the small-angle issue in xrt directly. we definitely will transfer the experience in xrt to the photons in PIConGPU.

**Closed** 2017-04-13 15:21 UTC
Labels: duplicate, question
