### ISSUE TITLE
mpiInfo build on master failing

### ISSUE THREAD

**Issue by anshumang** [ComputationalRadiationPhysics/picongpu#1059] opened 2015-08-25 19:46 UTC
Building NVCC (Device) object build_picongpu/build_cuda_memtest/CMakeFiles/cuda_memtest.dir//./cuda_memtest_generated_cuda_memtest.cu.o
[ 66%] Building CXX object build_picongpu/build_mpiInfo/CMakeFiles/mpiInfo.dir/main.cpp.o
/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/src/mpiInfo/main.cpp: In function 'int main(int, char**)':
/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/src/mpiInfo/main.cpp:158:9: error: 'cerr' is not a member of 'std'
         std::cerr << desc << "\n";
         ^
/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/src/mpiInfo/main.cpp:164:9: error: 'cout' is not a member of 'std'
         std::cout << "mpi_host_rank: " << getHostRank( ) << std::endl;
         ^
/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/src/mpiInfo/main.cpp:166:9: error: 'cout' is not a member of 'std'
         std::cout << "mpi_rank: " << getMyRank( ) << std::endl;
         ^
/ccs/home/anshuman/ComputationalRadiationPhysics/picongpu-repos/08-25-2015/picongpu/src/mpiInfo/main.cpp:168:9: error: 'cout' is not a member of 'std'
         std::cout << "mpi_size: " << getTotalRanks( ) << std::endl;
         ^
make[2]: *** [build_picongpu/build_mpiInfo/CMakeFiles/mpiInfo.dir/main.cpp.o] Error 1
make[1]: *** [build_picongpu/build_mpiInfo/CMakeFiles/mpiInfo.dir/all] Error 2

System details -
Titan (SUSE Linux Enterprise Server 11 (x86_64), cmake 2.8.10.2, gcc 4.8.2, nvcc 6.5.12, boost 1.57.0)
Commit # ac82b4c96d5659380042b0e61f14092961e36120

**Comment by ax3l** [comment] 2015-08-26 16:12
@anshumang thank you for the report!

the problem is already fixed in the current dev and you just need to add the line `#include <iostream>` into `src/mpiInfo/main.cpp`:
```diff
diff --git a/src/mpiInfo/main.cpp b/src/mpiInfo/main.cpp
index 201ea22..2eef4af 100644
--- a/src/mpiInfo/main.cpp
+++ b/src/mpiInfo/main.cpp
@@ -20,6 +20,7 @@
 
 #include <mpi.h>
 #include <cstdlib>
+#include <iostream> // std::cerr
 
 #include <boost/program_options.hpp>
 #include <boost/program_options/options_description.hpp>
```

**Closed by ax3l** 2015-08-26 16:12 UTC
Labels: affects master, bug, tools

**Comment by anshumang** [comment] 2015-08-26 16:14
@ax3l Thanks !
I was running PIConGPU on Titan after a while and noticed that the cmake version required to run dev is not available on Titan...just fyi....

**Comment by ax3l** [comment] 2015-08-26 16:14
ah absolutely, that is also how I spotted it for the fix in #786 :)

sorry for the inconveniences!

**Comment by ax3l** [comment] 2015-08-26 16:18
@anshumang regarding cmake: our current `dev` (and the next release) require cmake `2.8.12.2+`.
you can run with either the modules `cmake3/3.1.0` or `cmake3/3.2.3` on titan :)

**Comment by anshumang** [comment] 2015-08-26 16:19
@ax3l Great, thanks :+1:

**Comment by ax3l** [comment] 2015-08-26 16:21
all right, if there is any further trouble with, e.g., cmake `3.X` on Titan feel free to open an other issue. thanks for reporting! :sparkles:

**Comment by anshumang** [comment] 2015-08-26 16:24
will do...thanks for following up ! :satisfied:
