### ISSUE TITLE
runtime error on topic-collisions "illegal memory access"

### ISSUE THREAD

**Issue by paschk31** [ComputationalRadiationPhysics/picongpu#3381] opened 2020-10-13 15:52 UTC
got runtime error:

```Unhandled exception of type 'St13runtime_error' with message '/home/paschk31/src/picongpu/thirdParty/cupla/alpaka/include/alpaka/event/EventUniformCudaHipRt.hpp(198) 'ret = ALPAKA_API_PREFIX(EventQuery)( event.m_spEventImpl->m_UniformCudaHipEvent)' returned error  : 'cudaErrorIllegalAddress': 'an illegal memory access was encountered'!', terminating```

occured while being on branch(@pordyna):
https://github.com/pordyna/picongpu/tree/topic-collisions

first made a simulation without the Collision.param, which went smoothly
then made a simulation with Collision.param, which gave the above error (param and cfg are identical to before)

already discussed with @n01r

**Comment by sbastrakov** [comment] 2020-10-15 08:06
Thanks for reporting @paschk31 . Could you provide your exact setup: which commit was used, and which .param and .cfg files. We can enable some debug checks and that hopefully would give more info on what went wrong.

**Comment by paschk31** [comment] 2020-10-15 10:42
@sbastrakov yes like u guessed it happend on hemera5
commit:  f2c450e1d5e934d065cb475a9fdceb2d1819893d
input set: [input_collision.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/5383922/input_collision.zip)

**Comment by pordyna** [comment] 2020-10-15 11:57
actually the commit was: 491daef0e7f36894e1ade8cbd3d9cb8e7d633ab0

**Comment by sbastrakov** [comment] 2020-10-15 12:04
Okay, starting to look right now. What was the Hemera partition?

**Comment by pordyna** [comment] 2020-10-15 12:19
It was `gpu`. We tried running it on `k80` with a smaller box and less macro particles but it didn't help. I just tried LWFA  on `k20` with Ions, collisions on and got the same error. Now I'm trying LWFA again with a much smaller particle box.

**Comment by sbastrakov** [comment] 2020-10-15 15:39
Yes, looks the same for me. Generally, I think we should also make some more hierarchical PIConGPU error handling to e.g. know what stage failed and not just something failed.

**Comment by sbastrakov** [comment] 2020-10-15 15:45
If this is the case, it may be actually harmful for debugging? And so alpaka may need a similar mechanism or option to throw vs. print and throw? @psychocoderHPC

**Comment by psychocoderHPC** [comment] 2020-10-15 16:46
> If this is the case, it may be actually harmful for debugging? And so alpaka may need a similar mechanism or option to throw vs. print and throw? @psychocoderHPC

Yes we need to catch the error and provide our message.

**Comment by sbastrakov** [comment] 2020-10-19 15:33
Sorry it took long, but with #3396 we should have more informative error messages when a crash happens inside of a kernel. This works only when the option `PMACC_BLOCKING_KERNEL` is enabled (which it should be for debugging), e.g. like `pic-build -c "-DPMACC_BLOCKING_KERNEL=ON"`. I think you could already take these changes and put on the branch in question, it's all in one file.

**Comment by pordyna** [comment] 2020-10-23 11:03
With the LWFA example, ions on and  ionisation disabled. 
* ` ./bin/picongpu -d 1 1 1 -p 0 0 1 -g 192 1024 36 -s 100 ` crashes  at 78%
* ` ./bin/picongpu -d 1 1 1 -p 0 0 1 -g 96 1024 36 -s 100 `  runs
* ` mpi-exec -n 2 ./bin/picongpu -d 2 1 1 -p 0 0 1 -g 192 1024 36 -s 100 `  crashes at 84%
* ` mpi-exec -n 4 ./bin/picongpu -d 4 1 1 -p 0 0 1 -g 192 1024 36 -s 100 `  crashes at 65%

So it doesn't really look like it is just not enough memory. with "-DPMACC_BLOCKING_KERNEL=ON" it says that it crashes at the collision kernel.

**Comment by pordyna** [comment] 2020-10-23 12:44
I tried running it with `cuda-memcheck` but I didn't learn much from it. Maybe I need to set some extra compile flags? @sbastrakov @psychocoderHPC  what do you think? 
[memcheck.log](https://github.com/ComputationalRadiationPhysics/picongpu/files/5429463/memcheck.log)

**Comment by sbastrakov** [comment] 2020-10-26 09:51
> So it doesn't really look like it is just not enough memory. with "-DPMACC_BLOCKING_KERNEL=ON" it says that it crashes at the collision kernel.

@pordyna okay, so I believe the output should now be trustworthy. I believe as a super-naive way of narrowing down the issue, one could gradually disable or comment out parts of that kernel? E.g. with a dichotomy approach: remove the second "half", then the second half of the failing half, etc.

**Comment by pordyna** [comment] 2020-10-27 14:46
@sbastrakov @HighIander  so I was able to narrow it down a little bit. I tried to run my thermalization simulation with more cells and it still runs. Initially field solver, current and pushers were disabled. So I enabled all 3 and it crushed. With the Yee solver enabled, species needed to have both a current and a pusher attribute to trigger a crush.
I tried disabling the current and the pusher in my previous LWFA setup and the simulation was running for 1000 step, no error! The only difference to my  thermalization case: For LWFA disabling/enabling  current doesn't change anything. Error occurrence depends solely on a pusher.  

I'm quite confused with this. Do you have any ideas? The error happens in the `IntraCollisions` kernel (same species) so the next thing for me would be to check if anything happens when there are only inter-species collisions on.

**Comment by sbastrakov** [comment] 2020-10-27 14:55
Just as a thought while reading your message. In case the particle pusher is used, there is also `fillAllGaps` called. Could it be that there is some problem in collisions that does not take into account that the last frame is not full? (Or it just does not call `fillAllGaps` afterwards)?

**Comment by psychocoderHPC** [comment] 2020-10-27 15:00
Take care https://github.com/pordyna/picongpu/blob/921902f80230370517bc9769f0eb8f1325f3029f/include/picongpu/particles/collision/IntraSpecies.hpp#L226 is only active if you not compile as release mode.

Am 27. Oktober 2020 15:46:45 MEZ schrieb "Paweł Ordyna" <notifications@github.com>:

**Comment by pordyna** [comment] 2020-10-27 15:04
@psychocoderHPC I have removed this asserts already, since they won't work on device side anyway.  I should put there an if statement for now.

**Comment by psychocoderHPC** [comment] 2020-10-27 15:09
Is this part of the code executed if there is only one particle in the cell?

**Comment by pordyna** [comment] 2020-10-27 15:10
@sbastrakov I do sth like this:
```
auto & superCell = pb.getSuperCell( superCellIdx );
uint32_t numParticlesInSupercell = superCell.getNumParticles();

I'm not calling `fillAllGaps' in my kernel, should I? what does it do exactly?
```
and check if ` frameId * framSize + index <  numParticlesInSupercell'

**Comment by pordyna** [comment] 2020-10-27 15:11
@psychocoderHPC I was just thinking about it. I think yes. This could explain it. It definitely shouldn't be.

**Comment by sbastrakov** [comment] 2020-10-27 15:13
@pordyna then I think you are fine there. `fillAllGaps` is called from the host side after a kernel that can delete particles or move them between super cells (the latter happens after particle pusher and moveAndMark)

**Comment by pordyna** [comment] 2020-10-27 16:07
@sbastrakov @psychocoderHPC It looks like this was it. It runs.  I was either colliding with just one particle ( int intra-collisions), or with zero particles in in the shorter list (inter-collisions). Before I was only checking if the longer list is not empty.

**Comment by psychocoderHPC** [comment] 2020-10-27 16:32
@pordyna You can close the issue if it is solved.

**Comment by pordyna** [comment] 2020-10-30 14:49
I think only @paschk31 can close it.

**Comment by sbastrakov** [comment] 2020-10-30 14:52
Technically we can also click the button as maintainers. We just don't know if the issue is resolved.

**Closed** 2020-11-01 12:33 UTC

**Comment by Theodotus1243** [comment] 2022-05-09 10:58
Have the same problem after turning on collisions

picongpu@0.6.0 spack installation
ubunu 20.04, nvidia-driver r-510, GPU rtx-2080(non-cluster)

With variying input parameters crash heppens in different time, or not crashing
Input: [input.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/8651006/input.zip) (LWFA variation)
___
Can send extended log(please say how)
Or if some intermidiate fixes already implemented on 0.7.0-dev prease say it too

**Comment by sbastrakov** [comment] 2022-05-09 11:03
Oh that is interesting, thanks for reporting @Theodotus1243 .

We (well, at least I) thought the issue is solved in 0.6.0, but apparently not. I am not sure if there were changes that could affect it since the 0.6.0 release, do you know @psychocoderHPC ?

A log - please do send it. If too large to be attached to a github issue, could you upload it to some open github repository or public filesharing like google drive and share the link?

**Comment by psychocoderHPC** [comment] 2022-05-09 12:19
@Theodotus1243 If you enable collision the memory footprint on GPU will increase compared to a simulation without collision.
The error in the initial post mostly points to out-of-memory on GPU during the runtime.
Mostly the only way to solve the issue is to reduce the simulation size by reducing the number of cells or the number of particles per cell.

**Comment by Theodotus1243** [comment] 2022-05-10 15:10
@psychocoderHPC @sbastrakov thanks, my bad

I have previosly set this
By reducing PPC twice or by increasing memory limit from 3GiB -> 350MiB the problem has been solved
```
constexpr size_t reservedGpuMemorySize = 3ull *1024*1024*1024; //Set 3 GiB free
```
___
But then two questions
1) `reservedGpuMemorySize` is hard limit or soft limit
2) Does collisions memory requirement insrease is dynamic, or somehow static(for me increase appears from 5GiB -> 7.5GiB)

**Comment by psychocoderHPC** [comment] 2022-05-11 06:27
> 1. reservedGpuMemorySize is hard limit or soft limit

It is a hard limit, if you change `reservedGpuMemorySize` from 350MiB to 3GiB this means on a GPU with 16GiB main memory you will use with PIConGPU only 13GiB. CUDA requires during the runtime some additional memory on the GPU to store the context and some small additional data, therefore we keep by default 350MiB free, mean PICOnGPU is not allowed to touch this memory because it is reserved for the CUDA driver. IF you change this value to something large as 3GiB this means you have less memory for you simulation setup. 
Since you are running on a consumer GPU I am not sure if the XServer is also running on this GPU, if sou increasing `reservedGpuMemorySize` is useful to keep some memory on the GPU for the XServer free.

> 2. Does collisions memory requirement insrease is dynamic, or somehow static(for me increase appears from 5GiB -> 7.5GiB)

The memory requirements are dynamically and depends on the GPU device and your setup. Over the thump based of the current implementation of collision, the additional memory required during the runtime of the collision algorithm is `numParticlesPerGPU * 4byte * 2`.
