### ISSUE TITLE
Precission

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3917] opened 2021-11-19 12:00 UTC
I know that PIConGPU works with two precision levels:

```
/*! Select a precision for the simulation data
 *  - precision32Bit : use 32Bit floating point numbers
 *                     [significant digits 7 to 8]
 *  - precision64Bit : use 64Bit floating point numbers
 *                     [significant digits 15 to 16]
 */
```
In my case I need a spatial precision down to 0.1 nanometre so the 10th digit. The computational time is greatly reduced selecting the ```32Bit``` option and I guess the memory engagement as well and this would allow me to enforce the mesh quality. On the other hand if the ```32Bit``` option cannot resolve 0.1 nm it is not so safe to use it in my case. I know that this is a problem of low level machine language format and we are limited to these two option.

Nevertheless, could you confirm that the 7-8 digits apply to any quantity that ```PIConGPU``` writes out, or maybe only to particles?

Thank you.

**Comment by pordyna** [comment] 2021-11-19 12:22
Well length scales are in `UNIT_LENGTH` and this is equal to the time step duration times the speed of light. So as long as your time step is scaling with the cell size (as it needs to satisfy the CFL condition. So as far as I now, it shouldn't really matter if you simulate on nm or km scale. The conversion factor from pic units to SI units (in the output) is always stored in double precision.

**Comment by cbontoiu** [comment] 2021-11-19 12:27
> Well length scales are in `UNIT_LENGTH` and this is equal to the time step duration times the speed of light. So as long as your time step is scaling with the cell size (as it needs to satisfy the CFL condition), as far as I now, it shouldn't really matter if you simulate on nm or km scale. The conversion factor from pic units to SI units (in the output) is always stored in double precision.

Indeed I synchronize ```DELTA_T_SI``` with the ```CELL_WIDTH_SI```, ```CELL_HEIGHT_SI``` and ```CELL_DEPTH_SI``` and the CFL conditions is always fulfilled.

**Comment by sbastrakov** [comment] 2021-11-22 14:39
I agree with @pordyna 's reply.

To reiterate/extend, when comparing 32-bit vs. 64-bit there is a difference in both the number of significant digits (due to number of bits for mantissa) and range of represented magnitudes (due to number of bits for exponential value).

Magnitudes should generally be no problem even in 32 bits due to internal normalization used by PIConGPU and that each particular PIC simulation generally doesn't feature that different scales. Regarding mantissa bits, it should mostly be not a problem in 32 bits as well, because general errors in PIC simulation due to finite-difference schemes and sampling with particles are of a larger order of magnitude. Again, this is taking into account the coordinate storage used by PIConGPU to optimize for it, in case a naive storage was used, maybe it would be problematic.

A situation when one needs 64 bits in core PIConGPU is when there is some sort of numerical instability caused by floating-point arithmetic (like cancellation happening and 32-bit mantissa is too short) and that is not resolved with 32 bits. Note that some other parts, like radiation calculation, which may by more sensitive to floating-point than general PIC loop, normally have their own settings of precision.

**Comment by cbontoiu** [comment] 2021-11-22 16:46
Thanks @pordyna  and @sbastrakov 

Indeed I checked and there is no difference for the fields
![image](https://user-images.githubusercontent.com/7108691/142901334-953f5848-d5b5-4d71-8063-c0e2c48e7e6c.png)
There is some small difference for the electrons charge density confined within 0.34 nm thick layer and displaced by the laser, but I can live with this.  
![image](https://user-images.githubusercontent.com/7108691/142901164-d93a9e33-b96e-4d7f-a32f-db724df64dfa.png)

**Comment by steindev** [comment] 2021-11-25 08:26
As it seems, the issue is settled. I will close now. @cbontoiu please re-open or open a new issue if you have further questions regarding this topic.

**Closed by steindev** 2021-11-25 08:26 UTC
Labels: question
