### ISSUE TITLE
Introduce dust into the target

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#4189] opened 2022-06-29 13:25 UTC
Hi,

I wish to introduce dust particles into the target. The position of the dust is random. How could I do it using freeformular? Thanks.

```
namespace densityProfiles
{
    struct DustFunctor
    {
        /** This formula uses SI quantities only.
         *  The profile will be multiplied by BASE_DENSITY_SI.
         *
         * @param position_SI total offset including all slides [meter]
         * @param cellSize_SI cell sizes [meter]
         *
         * @return float_X density [normalized to 1.0]
         */
        HDINLINE float_X
        operator()(
            const floatD_64& position_SI,
            const float3_64& cellSize_SI
        )
        {
            // m -> mu
            const float_64 y( position_SI.y() * 1.e6 );
            const float_64 x( position_SI.x() * 1.e6 );
    
            constexpr float_64 RADIUS = 1.0; // in micrometer
            
            center = Random??

            float_64 r = math::sqrt(( x-center )*( x-center ) + ( y-center )*( y-center ));
            
            float_64 dens = 0.0;

            if( r <= RADIUS  )
              dens = 1.0;
            
            // safety check: all parts of the function MUST be > 0
            dens *= float_64( dens >= 0.0 );
            return dens;
        }
    };

    // definition of free formula profile
    using Dust = FreeFormulaImpl< DustFunctor >;

} // namespace densityProfiles
} // namespace picongpu
```

**Comment by sbastrakov** [comment] 2022-06-29 14:14
Hello @StevE-Ong ,

I am not sure I understand your use case. From the code sample you provided, it seems you would just like to sample the `center` variable somehow according to the use case. If we imagine it is done, then performing `CreateDensity<Dust, ...>` would call your `DustFunctor` independently for each PIConGPU cell. Each call will have its own `center` sampled and so you would have no way to know which centers were "chosen" by all other cells. So i am not sure how the result of this operation could be interpreted, as basically your density function is itself non-deterministic wrt center sampling. Sorry if I misunderstand something.

Can you operation be expressed just as sampling from a deterministic spatial density function `f(x)`, perhaps parametrized with center positions but those positions pre-selected somehow? Especially if you have a small number of them, could be even hard-coded in a helper array.

**Comment by StevE-Ong** [comment] 2022-06-29 14:19
Hi, @sbastrakov 

I was trying to do something like this. I assume the dust has a circle shape and distribute in the simulation region randomly.

![Figure 56](https://user-images.githubusercontent.com/52823653/176459259-de11989f-371a-4076-921b-fd5364f0aab8.png)

**Comment by sbastrakov** [comment] 2022-06-29 14:23
Okay, and how many circles do you have by order of magnitude?

**Comment by StevE-Ong** [comment] 2022-06-29 14:30
The number of circle can be set arbitrary. Imagine a gas jet or solid target dope with impurities (i.e. 1e13 particles/cm**3). In principle I can do it by using FromOpenPMD, where the profile is created elsewhere. That is sufficient for solid target. I am not sure for gas jet where the moving window will be used.

**Comment by sbastrakov** [comment] 2022-06-29 14:57
So loading density values from a file is always possible. For that a user is not limited to initialization start pipeline, it can be done for a selected time step(s) as part of iteration start pipeline. Practically that may be a good solution.

If you want to use an own density functor in spirit of the code sample posted, I think there is no way around somehow pre-generating and storing center positions. I do not think the way you originally drafted is suitable for that in principle, as, again, then cells are independent of one another and so each cell would effectively behave as if it had another circle. Instead, this operation could in principle be expressed as follows (How practically easy depends on your familiarity with PIConGPU, if needed i can help further):

```cpp
struct DustFunctor
{
    uint32_t numCenters; // number of centers in the local domain, will also be accessible in operator()
    floatD_X* centers; // device pointer to center positions in the local domain, will also be accessible in operator()

    // This constructor (when provided) will be called on the host side when calling CreateDensity<DustFunctor,...>
    // It will be called on each local domain
    HINLINE DustFunctor(uint32_t currentStep)
    {
         // choose numCenters
         // make a PIConGPU host-device buffer to store numCenters values of floatD_X
         // get host pointer to it
         // use it to initialize center values
         // copy to device
         // take device pointer and save in member centers
    }
    
    HDINLINE float_X operator()(...)
    {
         // dens = 0.0;
         // Loop over all numCenters centers:
        //       if we are close enough to current center, set dens to 1.0
    }
};
```

**Comment by StevE-Ong** [comment] 2022-07-01 07:26
Thanks @sbastrakov 
I tried this 
```
struct DustFunctor
{
        /** This formula uses SI quantities only.
         *  The profile will be multiplied by BASE_DENSITY_SI.
         *
         * @param position_SI total offset including all slides [meter]
         * @param cellSize_SI cell sizes [meter]
         *
         * @return float_X density [normalized to 1.0]
         */
        HDINLINE float_X
        operator()(
            const floatD_64& position_SI,
            const float3_64& cellSize_SI
        )
        {
            // m -> mu
            const float_64 y( position_SI.y() * 1.e6 );
            const float_64 x( position_SI.x() * 1.e6 );
            constexpr float_64 RADIUS = 1; // in micrometer
            
            float_64 dens = 0.0;

            for(uint32_t d = 0; d < 5; ++d)
                {
                    float_64 r = math::sqrt((x-d)*(x-d) + (y-d)*(y-d));

                    if( r <= RADIUS )
                        dens = 1.0;
                }
            
            // safety check: all parts of the function MUST be > 0
            dens *= float_64( dens >= 0.0 );
            return dens;
        }
};
// definition of free formula profile
using Dust = FreeFormulaImpl< DustFunctor >;
```
With the following result

<img src="https://user-images.githubusercontent.com/52823653/176845052-0d46f686-35da-405e-99e4-1fcc10cc114b.png" width="200" height="400" />

If `d` is a list of random number to loop for it will be enough.

**Comment by sbastrakov** [comment] 2022-07-01 07:59
Sorry if the following is stupid, I have a feeling that I am missing something, or my previous replies were confusing. Now I will try to explain how I see this issue.

With your last code sample, the dust centers are fixed. So each call to the `operator()` will have centers at `(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)` in micrometers. Then all the cells close enough to one (or more) of the centers will get `dens = 1.0` and all works fine, as your attached image also shows. 

However, it is only fine as long as all calls to `operator()` operate with the same centers. So if one modified your functor to  something like
```cpp
...
for(uint32_t d = 0; d < 5; ++d)
{
    float_64 xc = somehow_get_random_center_x();
    float_64 yc = somehow_get_random_center_y();
    float_64 r = math::sqrt((x-xc)*(x-xc) + (y-yc)*(y-yc));
...
```
it would *not* work (if the centers are actually random). The problem is not how to get a random number generator there and implement those functions. But that each call to `operator()` will have its own, different, sets of values of `xc, yc`. And we call it for each PIConGPU cell, so basically each cell will operate with its own centers, that are not consistent with all other cells. So some cells will randomly have particles and some won't but there will be no circular pattern at all.

My previous code sample was designed to alleviate this problem by generating the centers once on the host side. That would allow all the cells (= all calls to the `operator()`) to operate with the same set of centers. From my understanding, this is what you want to accompish and I think it's the easiest way to do it.

**Comment by StevE-Ong** [comment] 2022-07-04 08:21
If I understand correctly, a list random center positions is first generated elsewhere. Then, the center is loaded in the loop.

**Comment by sbastrakov** [comment] 2022-07-04 09:02
Yes, and I think that is the only way for your case.

**Comment by StevE-Ong** [comment] 2022-07-04 10:28
I see. I am not very familiar with the code and probably need help with these lines

```
struct DustFunctor
{
    uint32_t numCenters; // number of centers in the local domain, will also be accessible in operator()
    floatD_X* centers; // device pointer to center positions in the local domain, will also be accessible in operator()

    // This constructor (when provided) will be called on the host side when calling CreateDensity<DustFunctor,...>
    // It will be called on each local domain
    HINLINE DustFunctor(uint32_t currentStep)
    {
         // choose numCenters
         // make a PIConGPU host-device buffer to store numCenters values of floatD_X
         // get host pointer to it
         // use it to initialize center values
         // copy to device
         // take device pointer and save in member centers
    }
```

**Comment by sbastrakov** [comment] 2022-07-04 11:36
Sure, please find a prototype below.

```cpp
...
// Add to what is already included in your density.param
#include <pmacc/memory/buffers/HostDeviceBuffer.hpp>
#include <random>
...
        struct DustFunctor
        {
            //! Number of centers in the local domain, initialized on host and will be accessible in operator()
            uint32_t numCenters;

            //! Device pointer to center positions [micrometer] in the local domain, to be used in operator()
            floatD_X* centers;

            //! Host-side constructor, will be called once per each MPI rank
            HINLINE DustFunctor(uint32_t const currentStep)
            {
                // Select number of centers per MPI rank
                // If needed, this value can be taken from compile-time parameters
                // in a similar way to PARAM_BASE_DENSITY_SI, etc., see cmakeFlags for that
                numCenters = 100;

                // Make a host-device buffer to store centers, this allocates memory on both host and device
                auto bufferSize = pmacc::DataSpace<1>{static_cast<int>(numCenters)};
                pmacc::HostDeviceBuffer<floatD_X, 1> buffer(bufferSize);

                // Take pointer to host memory
                floatD_X* hostCenters = buffer.getHostBuffer().getPointer();

                // Initialize values on host.
                // You can implement the logic you want here in "normal C++", not the usual PIConGPU parallel kernel way.
                // Currently we simply generate randomly uniformly everywhere for illustration.
                // For that we have to query information on the local domain (= current MPI rank).
                auto const& subGrid = Environment<simDim>::get().SubGrid();
                auto const offsetCells = precisionCast<float_64>(subGrid.getLocalDomain().offset);
                auto const sizeCells = precisionCast<float_64>(subGrid.getLocalDomain().size);
                auto const cellSizeSI = floatD_64{SI::CELL_WIDTH_SI, SI::CELL_HEIGHT_SI};
                auto const minCenterPosition = offsetCells * cellSizeSI * 1.e6 ; // [micrometer]
                auto const maxCenterPosition = (offsetCells + sizeCells) * cellSizeSI * 1.e6 ; // [micrometer]
                // Here we have no access to PIConGPU random functionality, but can use standard C++ routines
                std::random_device rd;
                std::mt19937 gen(rd()); // for same dust position between runs replace rd() with a constant value
                std::uniform_real_distribution<float_64> distributionX(minCenterPosition[0], maxCenterPosition[0]);
                std::uniform_real_distribution<float_64> distributionY(minCenterPosition[1], maxCenterPosition[1]);
                for (uint32_t i = 0; i < numCenters; i++)
                {
                    hostCenters[i][0] = static_cast<float_X>(distributionX(gen));
                    hostCenters[i][1] = static_cast<float_X>(distributionY(gen));
                }

                // Copy data from host to device
                buffer.hostToDevice();

                // Save device pointer to the member, so that we can access it in operator()
                centers = buffer.getDeviceBuffer().getPointer();
            }

            /** This formula uses SI quantities only.
             *  The profile will be multiplied by BASE_DENSITY_SI.
             *
             * @param position_SI total offset including all slides [meter]
             * @param cellSize_SI cell sizes [meter]
             *
             * @return float_X density [normalized to 1.0]
             */
            HDINLINE float_X
            operator()(
                const floatD_64& position_SI,
                const float3_64& cellSize_SI
            )
            {
                // m -> mu
                const float_64 y( position_SI.y() * 1.e6 );
                const float_64 x( position_SI.x() * 1.e6 );
                constexpr float_64 RADIUS = 1; // in micrometer
                
                float_64 dens = 0.0;

                for(uint32_t d = 0; d < numCenters; ++d)
                {
                    auto const xc = centers[d].x();
                    auto const yc = centers[d].y();
                    float_64 r = math::sqrt((x - xc) * (x - xc) + (y - yc) * (y - yc));
                    if( r <= RADIUS )
                        dens = 1.0;
                }
                
                // safety check: all parts of the function MUST be > 0
                dens *= float_64( dens >= 0.0 );
                return dens;
            }
        };
        // definition of free formula profile
        using Dust = FreeFormulaImpl< DustFunctor >;
```

Here is the full file (with .txt added for github) 
[density.param.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/9039060/density.param.txt)

In my test it seems to produce a random pattern as attached 
![dust_test](https://user-images.githubusercontent.com/6825656/177146865-fafa1fd5-1c5b-4db9-be7b-9865c9fa6d0b.png)

**Comment by StevE-Ong** [comment] 2022-07-04 12:27
Thanks a lot. It does work.
<img src="https://user-images.githubusercontent.com/52823653/177153489-d33d098c-2032-4f1e-abce-c23090d0a51e.png" width="200" height="400" />

**Comment by sbastrakov** [comment] 2022-07-04 12:49
Great, I will close the issue then. Please feel free to reopen or open a new one if needed.

**Closed as completed by sbastrakov** 2022-07-04 12:49 UTC
Labels: question
