### ISSUE TITLE
openPMD-viewer all fields zero

### ISSUE THREAD

**Issue by Theodotus1243** [ComputationalRadiationPhysics/picongpu#4603] opened 2023-06-16 11:22 UTC
I have installed `picongpu@0.7.0-dev` with `spack`
The exact commit hash is around `68cd02685100e61571df769b08cbc25d854c9843`

I've runned this code [picInputs.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/11769482/picInputs.zip) and it produces png equal to `0.6.0`
But with `openPMD-viewer==1.7.0` I've got zeros for all fields
___
My setup is:
```
==> 50 installed packages
-- linux-ubuntu20.04-zen / gcc@10.3.0 ---------------------------
adios2@2.8.0          libffi@3.4.2          perl@5.34.1
autoconf@2.69         libiconv@1.16         picongpu@develop
automake@1.16.5       libpciaccess@0.16     pkgconf@1.8.0
berkeley-db@18.1.40   libpng@1.6.37         pmix@4.1.2
boost@1.79.0          libsigsegv@2.13       pngwriter@0.7.0
bzip2@1.0.8           libtool@2.4.7         popt@1.16
c-blosc@1.21.1        libxml2@2.9.13        readline@8.1
cmake@3.23.1          lz4@1.9.3             rsync@3.2.4
cuda@11.7.0           m4@1.4.19             snappy@1.1.8
diffutils@3.8         mpark-variant@1.4.0   sz@2.1.12
freetype@2.11.1       ncurses@6.2           util-macros@1.19.3
gdbm@1.19             nlohmann-json@3.10.5  xxhash@0.8.1
hdf5@1.12.2           numactl@2.0.14        xz@5.2.5
hwloc@2.7.1           openmpi@4.1.3         zfp@0.5.5
libedit@3.1-20210216  openpmd-api@0.14.5    zlib@1.2.12
libevent@2.1.12       openssh@9.0p1         zstd@1.5.2
libfabric@1.14.1      openssl@1.1.1o
```

**Comment by Theodotus1243** [comment] 2023-06-16 11:39
Maybe it's my ADIOS2 config, with may be deprecated for `0.6.0->0.7.0`

Or `adios2@2.8.0` with lots of bugs 

```
TBG_ADIOS2_configuration="'{                             \
   \"adios2\": {                                         \
       \"dataset\": {                                    \
           \"operators\": [ {                            \
               \"type\": \"blosc\"                       \
               , \"parameters\": {                       \
                   \"clevel\": \"1\"                     \
                   , \"compressor\": \"zstd\"            \
                   , \"doshuffle\": \"BLOSC_BITSHUFFLE\" \
               }                                         \
           } ]                                           \
       }                                                 \
       , \"engine\": {                                   \
           \"type\": \"file\"                            \
           , \"parameters\": {                           \
               \"BufferGrowthFactor\": \"1.1\"           \
               , \"InitialBufferSize\": \"4GB\"          \
               , \"AggregatorRatio\" : \"1\"             \
           }                                             \
       }                                                 \
   }                                                     \
}'"
```

**Comment by Theodotus1243** [comment] 2023-06-16 13:00
Here is the sample of saved data
[simData_200000.bp.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/11770488/simData_200000.bp.zip)

**Comment by Theodotus1243** [comment] 2023-06-16 13:37
Dropping compression helped
Leaving 
```
TBG_openPMD="--openPMD.period 100   \
             --openPMD.file simData \
             --openPMD.ext bp \
             --openPMD.range :,:,96:97"
```

**Comment by psychocoderHPC** [comment] 2023-06-16 14:09
@franzpoeschel Do you know out of the box what could be the issue here with the compression?

**Comment by franzpoeschel** [comment] 2023-06-16 14:38
Is it possible that you somehow installed openPMD-viewer with an ADIOS2 that does not support Blosc?
I can read the data from your uploaded file without any issue:

```
> bpls simData_200000.bp -d | head -n 10
  float     /data/200000/fields/B/x                                          {1, 256, 192}
    (0,  0,  0)    6.76239e-05 0.000254628 -7.29523e-05 0.000160257 0.0002497 -0.000554201
    (0,  0,  6)    -2.50284e-05 -0.000215694 -3.61948e-05 0.000309225 0.000327566 -0.000110322
    (0,  0, 12)    7.04143e-05 -2.67817e-05 -0.000281061 -0.00017045 -2.08328e-05 -2.95137e-05
    (0,  0, 18)    9.4932e-05 0.000414784 -5.04982e-05 -0.000151245 0.000159826 -0.000173264
    (0,  0, 24)    -8.32904e-06 8.6859e-05 0.00022245 -9.79506e-05 3.9881e-05 2.65058e-05
    (0,  0, 30)    -0.00010565 -0.000223883 -0.000415443 0.000170779 -0.000275402 0.000146991
    (0,  0, 36)    0.000125934 0.000301253 0.000343958 0.000156131 0.000452311 0.000239397
    (0,  0, 42)    0.000476538 3.9427e-05 -0.000380216 -0.000239045 -0.000144171 -5.4771e-05
    (0,  0, 48)    0.000298838 0.000100853 0.000188286 0.000141226 -0.000403177 -5.05176e-05
```

**Comment by Theodotus1243** [comment] 2023-06-17 06:30
@franzpoeschel Thanks
Right now I've tried to read the file from `picongpu` `0.6.0` vs `0.7.0-dev`

With `0.6.0`, the same compression algo and `openpmd-viewer==1.7.0` I opened a file normaly (it's 300MiB to upload here, as `0.6.0` don't support slicing)
With `0.7.0` all zeroes with compression, and working fine without

But then, you showed that even with compression the data is present 
___
I'm not sure then what is the right way to to install `openpmd-viewer`
Because I have `ADIOS2` in `spack`(I'm not sure if `openPMD-viewer` has some separate `ADIOS2` instance)
And `openPMD-viewer` in normal `pip` with `pip install openpmd-viewer`

**Comment by franzpoeschel** [comment] 2023-06-19 11:48
Using the Pip version of openPMD-api, I get the same problem:
```
>>> x = s.iterations[200000].meshes["E"]["x"][:]
>>> s.flush()                                                                  
>>> x                                                                          
array([[[0., 0., 0., ..., 0., 0., 0.],                                         
        [0., 0., 0., ..., 0., 0., 0.],                                         
        [0., 0., 0., ..., 0., 0., 0.],                                         
        ...,                                                                   
        [0., 0., 0., ..., 0., 0., 0.],                                         
        [0., 0., 0., ..., 0., 0., 0.],                                         
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)
```

Using a manually installed version, I see all the data:
```
>>> import openpmd_api as io
>>> s = io.Series("simData_%T.bp", io.Access.read_only)
>>> x = s.iterations[200000].meshes["E"]["x"][:]
>>> s.flush()
>>> x
array([[[-6.2377373e-04,  7.3486206e-04,  1.0711585e-04, ...,
          1.7572746e-04, -2.4745488e-04, -1.0231389e-03],
        [-7.9257152e-04,  6.9425162e-04,  1.4336938e-04, ...,
          1.3574339e-04, -5.6385371e-04, -1.0081133e-03],
        [-8.4184331e-04, -3.8581886e-05,  2.8852370e-04, ...,
         -7.6219486e-04, -1.2566526e-03, -1.1387664e-03],
        ...,
        [ 4.1600398e-04,  1.7821511e-03,  1.8251642e-03, ...,
          1.7601476e-04, -1.2797785e-03, -9.7129791e-04],
        [ 8.2058832e-04,  1.5028334e-03,  1.0580593e-03, ...,
         -6.6374615e-04, -6.1865576e-04,  4.1568212e-04],
        [ 2.9855402e-04,  5.4713362e-04,  4.2291475e-05, ...,
         -1.5568065e-04, -3.4651672e-04,  2.0648647e-04]]], dtype=float32)
```

Looking further into this, the `bpls` command from above will yield zeros only in ADIOS2 v2.7.1 (which is the version that our Pip package still ships with). I tested ADIOS2 v2.8.3 where the actual data is shown.

This looks like a bug in an old ADIOS2 version. We are currently trying to package the newest ADIOS2 version (https://github.com/openPMD/openPMD-api/pull/1387), so the best solution is to wait until that point and to use another configuration until then.

**Comment by steindev** [comment] 2023-06-19 18:35
I encountered that issue a few times. Typically the problem is different versions of blosc between writing and reading.

**Comment by franzpoeschel** [comment] 2023-06-19 18:37
In my above testing, I built ADIOS2 v2.8.3 and v2.7.1 with the same Blosc installation however

**Comment by steindev** [comment] 2023-06-27 12:21
@Theodotus1243 in principle your issue is resolved, right? Would you please close the issue if so?

**Closed as completed** 2023-06-27 14:13 UTC
